### ISSUE TITLE
安装印象笔记chrome插件后，出现bug

### ISSUE THREAD

**Issue by mrdream24** [surmon-china/vue-quill-editor#1]
安装印象笔记的剪藏插件后输入中文，然后点击粗体（或斜体等），再删除，会出现不能删除的bug。
这是quill这个库的一个问题，不能叫bug吧，因为作者表示这是插件的问题。
但是剪藏插件在中国的安装量还是很可观的，所以这个库如此的棒，因为这个小问题让我没办法用到生产环境，一直饮恨。
所以反应给你，看你有没有解决办法

**Comment by surmon-china** [comment]
我先测试下

**Comment by surmon-china** [comment]
经测试，这确实是印象笔记的剪切插件和quill库有冲突造成的，如果要解决，可能还是需要quill库做内部修复，我会进一步捕获错误，如果有新的进展会第一时间给quill提交pr

**Comment by surmon-china** [comment]
不建议修复问题，关闭。
