### ISSUE TITLE
Module parse error: node_modules\quill\dist\quill.snow.css Unexpected token (7:0) 

### ISSUE THREAD

**Issue by crow1796** [surmon-china/vue-quill-editor#10]
Why am I getting this error? I'm using default laravel 5.3 setup

`Module parse failed: C:\laragon\www\projectname\node_modules\quill\dist\quill.snow.css Unexpected token (1:0)   
You may need an appropriate loader to handle this file type.                                                 
| .ql-container {                                                                                            
|   box-sizing: border-box;                                                                                  
|   font-family: Helvetica, Arial, sans-serif;                                                               
 @ ./~/buble-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-quill-editor/editor.vue 6:0-36
 @ ./~/vue-quill-editor/editor.vue                                                                           
 @ ./~/vue-quill-editor/index.js                                                                             
 @ ./assets/src/js/admin/main.js./~/quill/dist/quill.bubble.css                                              `

**Comment by surmon-china** [comment]
Try adding style-loader and css-loader parsers in the webpack, and most of these errors are caused by the parser.

**Comment by surmon-china** [comment]
well.

**Comment by atomek1000** [comment]
Thanks @crow1796 !!

For anyone having same issues with VueQuillEditor / vue-quill-editor and using webpack vue cli 
here is another way to do it
```
import VueQuillEditor from 'vue-quill-editor'  
 components: { 
           VueQuillEditor:VueQuillEditor.quillEditor 
      },
```

**Comment by surmon-china** [comment]
```javascript
import { quillEditor } from 'vue-quill-editor'  
 components: { 
           VueQuillEditor: quillEditor
      }
}
```

**Comment by zainulmutaqin** [comment]
> ```js
> import { quillEditor } from 'vue-quill-editor'  
> components: { 
>       VueQuillEditor: quillEditor
> }
> ```

what file to located this syntax ?
