### ISSUE TITLE
browserify editor bundling error

### ISSUE THREAD

**Issue by jaideepdas** [surmon-china/vue-quill-editor#101]
I am getting an error using this component with vuejs cli browserify setup. Following is the error
`Error: Parsing file D:\workspace\viatrends\framework\fluux\client\engine\node_modules\vue-quill-editor\src\editor.vue: Unexpected token (1:0)`

my package.json
`{
  "name": "xxx",
  "version": "0.1.0",
  "description": "xxx",
  "author": "xxx",
  "private": true,
  "scripts": {
    "watchify": "watchify -vd -p browserify-hmr -e src/main.js -o dist/build.js",
    "serve": "http-server -o -c 1 -a localhost",
    "dev": "npm-run-all --parallel watchify serve",
    "build": "cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o dist/build.css ] -e src/main.js | uglifyjs -c warnings=false -m > dist/build.js"
  },
  "browserify": {
    "transform": [
      [
        "babelify",
        {
          "presets": [
            "es2015",
            "stage-2"
          ]
        }
      ],
      "vueify"
    ]
  },
  "browser": {
    "vue": "vue/dist/vue.common.js"
  },
  "dependencies": {
    "lodash": "^4.17.4",
    "q": "^1.5.0",
    "vue": "^2.0.1",
    "vue-formly": "^2.5.0",
    "vue-formly-bootstrap": "^2.2.7",
    "vue-input-tag": "0.0.16",
    "vue-quill-editor": "^2.3.3",
    "vue-resource": "^1.3.4",
    "vue-router": "^2.7.0",
    "vue-strap": "github:wffranco/vue-strap",
    "vue-upload-component": "^2.6.3",
    "vue2-filters": "^0.2.2"
  },
  "devDependencies": {
    "babel-core": "^6.0.0",
    "babel-plugin-transform-runtime": "^6.0.0",
    "babel-preset-es2015": "^6.0.0",
    "babel-preset-stage-2": "^6.0.0",
    "babel-runtime": "^6.0.0",
    "babelify": "^7.2.0",
    "browserify": "^13.1.0",
    "browserify-hmr": "^0.3.1",
    "cross-env": "^2.0.0",
    "envify": "^3.4.1",
    "http-server": "^0.9.0",
    "npm-run-all": "^2.3.0",
    "proxyquireify": "^3.0.1",
    "uglify-js": "^2.5.0",
    "vueify": "^9.0.0",
    "watchify": "^3.4.0"
  }
}
`

**Comment by jaideepdas** [comment]
@surmon-china hi any work around for this?

**Comment by surmon-china** [comment]
Sorry, just support webpack.
