### ISSUE TITLE
the  position of popup is bug after click video-button这个视频按钮点击后弹出层位置出现bug

### ISSUE THREAD

**Issue by zengjingke** [surmon-china/vue-quill-editor#104]
![image](https://user-images.githubusercontent.com/31331515/32095437-c5cecddc-bb35-11e7-8f6b-d650465b3b85.png)
en :the  position of popup is bug after click video-button
zh: 这个视频按钮点击后弹出层位置出现bug

**Comment by surmon-china** [comment]
你自己css的问题
