### ISSUE TITLE
Can't register module after Vue update to 2.5.3

### ISSUE THREAD

**Issue by ppietris** [surmon-china/vue-quill-editor#107]
After updating to Vue 2.5.3, I get the following error:

quill Cannot import modules/imageImport. Are you sure it was registered?

The Quill module is registered and this was working before the Vue update

**Comment by surmon-china** [comment]
https://github.com/surmon-china/vue-quill-editor/blob/master/examples/04-example.vue

![image](https://user-images.githubusercontent.com/14019524/32475522-12339692-c3ad-11e7-9c3a-1afbee4f0c4d.png)
