### ISSUE TITLE
Do you support Emojis?

### ISSUE THREAD

**Issue by demonmind** [surmon-china/vue-quill-editor#108]
I am trying to add emojis to the editor and was wondering if this was possible out of the box.

**Comment by surmon-china** [comment]
Quill does not support out of the box functionality, it provides an open module and api for developers to achieve functionality.

1. add insert emoji button  
    https://github.com/surmon-china/vue-quill-editor/blob/master/examples/03-example.vue

2. add insert emoji function

```javascript
insertEmoji(emoji) {
    const range = this.$refs.myEditor.quill.getSelection()
    this.$refs.myEditor.quill.insertText(range.index, emoji)
}

insertEmoji('🙂')
insertEmoji('😎')
```

**Comment by Form1ca** [comment]
any examples?
