### ISSUE TITLE
Trim white space automatically

### ISSUE THREAD

**Issue by Bloom2036** [surmon-china/vue-quill-editor#109]
## Example code here

html code 
```html
<quill-editor ref="myTextEditor" v-model="content"></quill-editor>
```

js code
``` javascript
<script>
  export default {
    data() {
      return {
        name: 'example',
        content: '<p>    Example</p>'
      }
    }
</script>
```

But the editor will trim the space before  '     Example',
How to prevent quill editor trim white space?

**Comment by surmon-china** [comment]
1. use '&nbsp;' to replace space. (The content will be `pasteHTML` by quill, not text.)

`<p>&nbsp;&nbsp;&nbsp; Example </p>`

2. add style `white-space: normal;`

quill Issues links:
https://github.com/quilljs/quill/issues/1751
https://github.com/quilljs/quill/issues/1752
https://github.com/quilljs/quill/issues/996

**Comment by Akitha** [comment]
Add this to styles.css

.ql-editor {
white-space: normal!important;
}
