### ISSUE TITLE
Inline formatting not working

### ISSUE THREAD

**Issue by crow1796** [surmon-china/vue-quill-editor#11]
Bold and Italic Formatting are not working, but the rest are working fine and also the html output is correct ![Output](http://image.prntscr.com/image/21435a0fc6484eeb99bd342430c58af4.png) 

Please help. Thanks!

**Comment by surmon-china** [comment]
Please post a detailed, context-sensitive code

**Comment by crow1796** [comment]
Sorry, I just noticed it now, I think my setup is the one that has an issue it doesn't display any html inline formatting. I'm gonna close this issue now. Anyway, Thanks for the reply :)
