### ISSUE TITLE
CSS resources should not be included automatically

### ISSUE THREAD

**Issue by k8n** [surmon-china/vue-quill-editor#111]
https://github.com/surmon-china/vue-quill-editor/blob/73cee12691a6cf08e2fbe839322168fe3b913c7a/src/editor.vue#L9-L11

There should at least be an option to alter this behaviour. Please. :-)

**Comment by surmon-china** [comment]
Update to v3.0.0 please.

https://github.com/surmon-china/vue-quill-editor/blob/master/CHANGELOG.md#v300
