### ISSUE TITLE
使用 modules/ImageResize 时, 点击左侧小方块图片会消失问题

### ISSUE THREAD

**Issue by feiguzi** [surmon-china/vue-quill-editor#112]
171行   偏移量有点问题,要改成  this.preDragWidth - (evt.clientX - this.dragStartX) ?

**Comment by surmon-china** [comment]
请将问题转移至：

https://github.com/kensnyder/quill-image-resize-module/issues/new

**Comment by lky559** [comment]
quill Overwriting modules/imageDrop with class ImageDrop {

	/**
	 * Instantiate the module given a quill instance and any options
	 * @param {Quill} quill
	 * @param {Object} options
	 */
	constructor(quill, options = {}) {
		// save the quill r…
