### ISSUE TITLE
How replace tags <font> and <b>?

### ISSUE THREAD

**Issue by willsilvano** [surmon-china/vue-quill-editor#115]
Hi friends!

I'm having a problem with paste text from other pages when it's contain old tags like `<font>` and `<b>`.

How can I replace these old tags to `<span>` or `<p>` tags?

When I paste this example, I lost the color green:

`<p><strong><font color="green">Inquire about VIP Status. *Existing clients ONLY!</font></strong></p>`

Thanks!

**Comment by surmon-china** [comment]
You can do this by customizing a quilljs module to listen to the clipboard and replace those labels before pasting.

https://github.com/kensnyder/quill-image-drop-module/blob/master/index.js#L21

https://quilljs.com/docs/modules/
