### ISSUE TITLE
Placeholder shows when content only contains white space or new lines.

### ISSUE THREAD

**Issue by ssoda** [surmon-china/vue-quill-editor#117]
### 中文用户注意：

1. 尽量用英文描述你的 issue
2. 不要把内容堆彻在标题上，逻辑清晰地写在内容区
3. 贴代码要提前格式化好，有颜色高亮那种，贴文本，不要贴图片
4. 提问题前，必须仔细阅读 REMADE.md + 在已关闭的问题中寻找与自身相关的问题，90% 的可能它已经被解决
5. **如果无法做到提一个合格、优秀的问题，则问题会被 close + block**

#### Vue.js version and component version
vue 2.4.4
vue-quill-editor 2.3.2
#### Reproduction Link
- A minimal JSBin, JSFiddle, Codepen, or a GitHub repository that can reproduce the bug.
- You could start with this template: https://jsfiddle.net/39epgLj0/

#### Steps to reproduce
1. Set some content in the editor
Assume the v-model name on editor is `content`
```
this.content = "<p>123</p>"
```

2. Then set `content` empty using white space(or new line). 
(**Do not type in the editor directly**, use Javascript controll it instead)
```
this.content = "<p> </p>"
// or try new line: this.content = "<p><br></p>"
```

3. The default placeholder will show, but the content is **not empty** exactly.
At this step, the v-model `content` **was emptied** when placeholder shows. (I didn't clear it)
#### What is Expected?		
The default placeholder should not show when the content only contains white space(or only new lines).

Because the `content` is `<p> </p>` or `<p><br><p>`, not empty.

當內容並非空白或者只有換行的情況，Placeholder 不應該顯示。
#### What is actually happening?
The placeholder shows when there is white space or new line.
Placeholder 在內容只有空白或換行的情況下，也會顯示。

**Comment by surmon-china** [comment]
https://github.com/quilljs/quill/issues/1235#issuecomment-273044116
https://github.com/quilljs/quill/issues/1328
https://github.com/surmon-china/vue-quill-editor/blob/master/src/editor.vue#L79

**Comment by ssoda** [comment]
Okay, so it looks like it's unabled to solve. Thanks for the reply!
I read official design [guide](http://quilljs.com/guides/designing-the-delta-format/)
It seems that the problem I encountered is a design limitation.
