### ISSUE TITLE
Unable to set size of image in initial content

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [surmon-china/vue-quill-editor#118]
Please i have tried to load an initial content image into the editor.
I have embedded style on  `img` but it is being removed when the component displays.

Please kindly show how we may set the size for `img` in initial content

**Comment by surmon-china** [comment]
This is not a component issue. This is the module requirement in the quill. If you are just changing the size, you can set the width property, which is valid but needs to be done if you want to change complex properties and styles.

1. `content: '<h1>content changed!</h1><p><img src="/vue-quill-editor/static/images/surmon-6.jpg" width="500" style=""></p>'`

2. https://github.com/quilljs/quill/issues?utf8=%E2%9C%93&q=style
