### ISSUE TITLE
whether i need import css by myself ?

### ISSUE THREAD

**Issue by CrazyHuiLiang** [surmon-china/vue-quill-editor#119]
I use vue-cli created my project(webpack template) and want to mount the editor in a component,
   
     "vue": "^2.5.2",    
     "vue-quill-editor": "^3.0.2",
i have set the webpack alias :

      'vue-quill-editor': 'vue-quill-editor/src/index.js',
i read your document
![2017-11-30 10 53 11](https://user-images.githubusercontent.com/12392813/33410822-0c4854ee-d5bd-11e7-9b39-dca9201df14b.png)
 I suppose your doc's mean if i use editor partly i don't need to import css files by myself, but i find if i don't import css i will loose the style;

my question is if i use editor partly , will the editor import automatism?

**Comment by surmon-china** [comment]
After v3.0.0, any use of components, you need to manually import css, which will be more conducive to your control of their package resources, and more convenient to complete the quill theme style customization; v3.0.0, the default output will be `dist/vue-quill-editor.js` as the core, UMD common format for AMD, CMD, commonjs and global.
