### ISSUE TITLE
html mode

### ISSUE THREAD

**Issue by kaznache** [surmon-china/vue-quill-editor#128]
is there any html mode?
I need to paste html to the editor

like I paste this block for example:
`<h1>Hello World!</h1>`
and get the same block
but now I get:
`<p>&lt;h1&gt;Hello World!&lt;/h1&gt;</p>`
or
`<pre class="ql-syntax" spellcheck="false">&lt;h1&gt;Hello World!&lt;/h1&gt; </pre>` - code mode

please help :)

**Comment by surmon-china** [comment]
In fact, quill defaults to html pastes, but since quilljs' rich text is based on the content of a particular class, even pasted output will still be reformatted. There should be no better solution to this problem.
