### ISSUE TITLE
图片存储问题

### ISSUE THREAD

**Issue by nevermore22** [surmon-china/vue-quill-editor#13]
集成的很不错~
我看到quill上是以base64自动存储在客户端
我后端该如何接受这张图片 目前直接接受经过base64后转码的字符串 但是再直接返回到客户端的时候就不能正常显示了.

**Comment by surmon-china** [comment]
“再次返回客户端时”的数据，截图

**Comment by surmon-china** [comment]
服务端接收数据时，可以用对应库将base64转为二进制文件存储，也可以直接以字符串形式存储base64，也可以是其他任何形式存储，输出给客户端时输出为绝对的文件路径地址，或者base字符串都可以

**Comment by nevermore22** [comment]
![qq 20170110102814](https://cloud.githubusercontent.com/assets/12908332/21791694/994dad82-d71f-11e6-86a0-999a88e462f9.png)

哦...! 
似乎在post的时候img里的src发生变化了 把里面的+号都编码为空格 导致我发送数据后再接受数据出错.
谢谢你的回答~

**Comment by surmon-china** [comment]
Nothing. 如果此问题解决，记得关闭问题~
