### ISSUE TITLE
image-resize 'imports'

### ISSUE THREAD

**Issue by MBearo** [surmon-china/vue-quill-editor#130]
![image](https://user-images.githubusercontent.com/23232655/34317698-264cd7fe-e7ef-11e7-8f71-60b8689b05eb.png)

**Comment by danielmlc** [comment]
同问

**Comment by surmon-china** [comment]
明显是：
自己 babel 配置
或 对应插件的问题，
这个问题，应该直接提在对应插件的 Issues 内
