### ISSUE TITLE
有時候，需要用在組件中，覆蓋全局的配置

### ISSUE THREAD

**Issue by zzzgit** [surmon-china/vue-quill-editor#131]
https://github.com/surmon-china/vue-quill-editor/blob/master/src/editor.vue#L77

只能擴展，不能覆蓋，這樣不方便
有時候，需要用在組件中，覆蓋全局的配置

**Comment by surmon-china** [comment]
可以覆盖的，`Object.assign({ a: 10, b: { c: 20 } }, { a: false, b: {} })`

**Comment by zzzgit** [comment]
我的意思是，想用組件內部的，完全替換全局的
用assign，全局中的部分設置還在，如果沒有被覆蓋的話

**Comment by surmon-china** [comment]
你可以在二级键值对使用空对象来覆盖全局对象的对应键值，这个合并策略无论怎样处理，都是有利有弊，所以只能取舍到一个平衡，大部分时候，全局配置是被高频复用的，所以目前使用了合并策略

**Comment by zzzgit** [comment]
okay

**Comment by surmon-china** [comment]
如果要覆盖的配置太多，也可以暂时这样 hack：
`<quill-editor :options="options" :global-options="{}"></quill-editor>`
