### ISSUE TITLE
关于内容适配移动端的问题

### ISSUE THREAD

**Issue by RoseEnd** [surmon-china/vue-quill-editor#136]
因为项目只在移动端展示，想问问后台编辑的富文本内容能否适配移动端，会不会出现样式问题?

**Comment by surmon-china** [comment]
quill 的样式里，大部分依赖 css class `ql-editor`，所以，一切 css 都是可以被覆盖和重写的，不会因为设备环境的不同而不同，所以，不会不兼容，不符合预期的直接覆盖就好。
