### ISSUE TITLE
vue.js?891f:523 [Vue warn]: Failed to mount component: template or render function not defined. 

### ISSUE THREAD

**Issue by fandudu** [surmon-china/vue-quill-editor#14]
vue.js?891f:523 [Vue warn]: Failed to mount component: template or render function not defined.

**Comment by surmon-china** [comment]
https://vuejs.org/v2/guide/installation.html#Standalone-vs-Runtime-only-Build

**Comment by fandudu** [comment]
![image](https://cloud.githubusercontent.com/assets/15722726/21883636/0f20c8ce-d8eb-11e6-9c8b-16f3aac52bf3.png)

**Comment by surmon-china** [comment]
I see you set the alias for the quill component, then how to call the component in the style of?

**Comment by fandudu** [comment]
![image](https://cloud.githubusercontent.com/assets/15722726/21884611/fe93bc38-d8ee-11e6-823d-71e32d38e57f.png)

**Comment by fandudu** [comment]
![image](https://cloud.githubusercontent.com/assets/15722726/21884642/1cc6305a-d8ef-11e6-9880-2a03476924c6.png)

**Comment by surmon-china** [comment]
```javascript
resolve: {
  alias: {
    'vue$': 'vue/dist/vue.common.js'
  }
}
```

vue$

Sorry, I can not determine for what reason; if you readme document in accordance with the use of the above will occur those mistakes?

**Comment by fandudu** [comment]
After a night,it successful without any code changed

**Comment by Jiiun** [comment]
![image](https://cloud.githubusercontent.com/assets/13991287/26033483/0c7aab08-38e0-11e7-8764-5407e1bca69c.png)
