### ISSUE TITLE
fastclick不兼容

### ISSUE THREAD

**Issue by hujindo123** [surmon-china/vue-quill-editor#141]
我是用fastclick  所有的事件都失效了  获取不到文本焦点 工具栏也获取不到   在fastclick文档中说是加入needsclick，在组件中是否有效呢 怎么解决

**Comment by surmon-china** [comment]
此类问题，请移步到 quill 官方。

https://github.com/quilljs/quill/issues?utf8=%E2%9C%93&q=fastclick
