### ISSUE TITLE
局部引入编辑器,组件一直编译失败?

### ISSUE THREAD

**Issue by milktea555** [surmon-china/vue-quill-editor#148]
JS代码如下:
<script>
  import vueQuillEditor from 'vue-quill-editor'
  import 'quill/dist/quill.core.css'
  import 'quill/dist/quill.snow.css'
  import 'quill/dist/quill.bubble.css'
  export default {
    components: {
      vueQuillEditor
    },
    data () {
      return {
        content: `<p><img src="/vue-quill-editor/static/images/surmon-6.jpg" width="500"></p>
                  <br>
                  <p><strong><em>Or drag/paste an image here.</em></strong></p>`,
        editorOption: {
          modules: {
            toolbar: [
              [
                {
                  'size':
                    ['small', false, 'large']
                }
              ],
              ['bold', 'italic'],
              [
                {
                  'list': 'ordered'
                },
                {
                  'list': 'bullet'
                }
              ],
              ['link', 'image']
            ],
            history: {
              delay: 1000,
              maxStack: 50,
              userOnly: false
            },
            imageDrop: true,
            imageResize: {
              displayStyles: {
                backgroundColor: 'black',
                border: 'none',
                color: 'white'
              },
              modules: [ 'Resize', 'DisplaySize', 'Toolbar' ]
            }
          }
        },
        activeChat: 1,
        user: {
          name: '',
          tel: '',
          mail: '',
          qq: '',
          textarea: ''
        }
      }
    },
    methods: {
      onEditorBlur (editor) {
        // console.log('editor blur!', editor)
      },
      onEditorFocus (editor) {
        // console.log('editor focus!', editor)
      },
      onEditorReady (editor) {
        // console.log('editor ready!', editor)
      }
    }
  }
</script>
HTML部分如下:
<vue-quill-editor v-model="content"
                          :options="editorOption"
                          @blur="onEditorBlur($event)"
                          @focus="onEditorFocus($event)"
                          @ready="onEditorReady($event)">
 </vue-quill-editor>
是不是少引入了什么?

**Comment by surmon-china** [comment]
粗心大意

**Comment by surmon-china** [comment]
https://github.com/surmon-china/vue-quill-editor#mount-with-component
