### ISSUE TITLE
报错：You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by clown-doll** [surmon-china/vue-quill-editor#15]
引用报这个错误：
ERROR in ./~/vue-quill-editor/editor.vue
Module parse failed: G:\catWork\CaseCollections-admin\node_modules\vue-quill-editor\editor.vue Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)

webpack里有对.vue的处理：
 {test: /\.vue$/, loader: 'vue', include: path.join(__dirname, 'src')}

**Comment by surmon-china** [comment]
It is recommended to use vue-cli to initialize your webpack project, otherwise there may be a variety of unpredictable problems.
