### ISSUE TITLE
SSR下，載入quill其他組件時，目前可正常運行的設置

### ISSUE THREAD

**Issue by jaelys** [surmon-china/vue-quill-editor#151]
Webpack 3.10 + Vue 2.5.13 +  vue-server-renderer 2.5.13
我修改了我的提問，感謝@surmon-china 觀念指導，受益匪淺
原提問標題 頁面重新整理會出現document is not defined，此問題無關vue-quill-editor及quill加載組件
原因為vue-router使用共用組件時路徑設置問題造成

以下分享在SSR模式時，載入quill其他組件時正常運行的代碼

**app.js使用SSR的範例，載入vue-quill-editor**
```
if(process.browser) { 
    let VueQuillEditor = require('vue-quill-editor/dist/ssr')
    Vue.use(VueQuillEditor)
}
```
**在組件 .vue中**
```
<script>
import { container,ImageExtend,QuillWatch } from "quill-image-extend-module"; //v1.1.1
import ImageResize from "quill-image-resize-module"; //v3.0.0
Quill.register("modules/imageExtend", ImageExtend);  
Quill.register("modules/imageResize", ImageResize);

export default {
editorOption: {
        modules: {
          imageResize: {
            displayStyles: {
              backgroundColor: "black",
              border: "none",
              color: "white"
            }
          },
         imageExtend:{ config },
         toolbar: container,
         handlers: {  //v1.1.0 up
              image: function() {                           
                  QuillWatch.emit(this.quill.id)                
              }
          } 
          ...
```
**webpack.comfig中**
```
rules: [
      {
          test: /\.js$/,
          loader: "happypack/loader?id=happybabel", //依照自己的loader設置
          exclude: /node_modules(?!\/quill-image-drop-module|quill-image-resize-module)/
        }

new webpack.ProvidePlugin({
                'window.Quill': 'quill',
                'Quill': 'quill/dist/quill.js',
              })
```

**Comment by surmon-china** [comment]
从表面看来，

1. ssr 中需要针对环境加载的资源，一定要使用 require 语句，且使用进程变量判断，而非 `window`
2. 我看到你的 rquire 语句缺少解构，也就意味着拿到的对象可能并非真正的 module
3. 每一个节点都需要调试，你给出的错误，我只有自己完全实现一遍才有可能复现

所以，我希望你能从不同以模块为节点一个个调试，给出更有用的信息及你自己的错误分析，祝好运。

**Comment by surmon-china** [comment]
同样的，这些模块也都需要判断环境变量，require 形式引入。

类似这样：

```javascript
if(process.browser) {
    const { container,ImageExtend, QuillWatch }, ImageExtendModule = "quill-image-extend-module"; 
    const ImageResize = "quill-image-resize-module";
    Quill.register("modules/imageExtend", ImageExtendModule.ImageExtend);  
    Quill.register("modules/imageResize", ImageResize);
}
```

**Comment by surmon-china** [comment]
其实，我也不清楚这个问题发生的真正原因，只能不断尝试。

**Comment by jaelys** [comment]
我之前嘗試使用
```
if (process.browser) { 
  const { container,ImageExtend, QuillWatch }= require("quill-image-extend-module"); 
  const ImageResize = require("quill-image-resize-module");
  Quill.register("modules/imageExtend", ImageExtend);  
  Quill.register("modules/imageResize", ImageResize);
}
```
都會出現
[Vue warn]: Error in directive quill inserted hook: "TypeError: moduleClass is not a constructor"

TypeError: moduleClass is not a constructor
    at SnowTheme.addModule (quill.js?c8f1:5366)
    at SnowTheme.addModule (quill.js?c8f1:6616)
    at eval (quill.js?c8f1:5358)
    at Array.forEach (<anonymous>)
    at SnowTheme.init (quill.js?c8f1:5356)
    at new Quill (quill.js?c8f1:1113)
    at inserted (ssr.js?b19c:54)
    at callHook$1 (vue.common.js?2371:6199)
    at callInsert (vue.common.js?2371:6138)
    at wrappedHook (vue.common.js?2371:2059)

後來改成import引入，就正常，但F5會document is not defined
我的觀念可能還是不夠好，我會再努力嘗試，感謝@surmon-china提點，如有嘗試成功，
我再來回報

感謝很棒的vue-quill-editor，讓我學習到很多

**Comment by surmon-china** [comment]
`"TypeError: moduleClass is not a constructor"`这个错误才是值得被解决的问题，极大可能是与你的 webpack 解构配置有关系的。我已经给你演示了，`Quill.register("modules/imageExtend", ImageExtendModule.ImageExtend);  `require 语句不要直接解构。

**Comment by jaelys** [comment]
```
const { container,ImageExtend, QuillWatch }, ImageExtendModule = "quill-image-extend-module"; 
const ImageResize = "quill-image-resize-module";
```
error
>  const { container,ImageExtend, QuillWatch }, ImageExtendModule = "quill-image-extend-module"; 
                                                                          ^
我原先有嘗試您指導的寫法，只是報錯語法錯誤，後來又改成require
另請教，webpack 解构配置能指導一下可能的方向嗎，我目前一直研究還是無法突破，謝謝您的指導

**Comment by surmon-china** [comment]
这个已经有过很多篇文章了，简单来说就是无论 ES Module，还是 nodejs 的 commonjs module 或 AMD、UMD，在被 webpack 读取时，都会转换为内部的模块结构，而 ES Module 中我们很多时候会暴露 default 对象，而不是真实对象，所以我们在引入一个模块（并调用时），webpack 会帮我们做自动分析，如果没有找到直接的对象，则会去 default 对象读取，如若再没有，则读取为空。

注意！是在使用这个对象时才回去寻找，但是 [ 解构 ] 是在一开始，也就是（也许）还没有赋值成功时，就已经对读到的空对象（在读 default 之前）进行解构，这时就会得到空对象，所以你要靠不同节点的打印来排查和解决问题。

上面这种情况一般发生在，所依赖的模块遵循的标准不一致的情况下会出现。

上面只是我的理解，或许有错误，批判看待，自己到 google 搜寻相关信息，不必依赖他人，很多问题都是已经有答案的，只等你去寻找。

**Comment by jaelys** [comment]
非常感謝@surmon-china，您的解說比大多數搜尋到的文章，讓人更容易理解正確的觀念，真的受益匪淺，
我會改變此問題標題及目前正常運行的設置，因為此標題已不在合適

**Comment by wfzong** [comment]
有完整的代码示例吗
