### ISSUE TITLE
添加链接出现的操作框中的文字‘Enter link’和‘save’可以做中文配置么？

### ISSUE THREAD

**Issue by jamesxieliang11** [surmon-china/vue-quill-editor#152]
### 中文用户注意：

1. 尽量用英文描述你的 issue
2. 不要把内容堆彻在标题上，逻辑清晰地写在内容区
3. 贴代码要提前格式化好，有颜色高亮那种，贴文本，不要贴图片
4. 提问题前，必须仔细阅读 REMADE.md + 在已关闭的问题中寻找与自身相关的问题，90% 的可能它已经被解决
5. **如果无法做到提一个合格、优秀的问题，则问题会被 close + block**

#### Reproduction Link
- A minimal JSBin, JSFiddle, Codepen, or a GitHub repository that can reproduce the bug.
- You could start with this template: https://jsfiddle.net/39epgLj0/

#### What is actually happening?

**Comment by surmon-china** [comment]
理论上都是可以改的，这个问题需要去 quill 的 issues 区域寻找答案，组件只是做了一层封装，遗憾的是我也没有在 quill issues 区域找到合适的答案。

**Comment by jamesxieliang11** [comment]
好的 谢谢

**Comment by jl1014171068** [comment]
// quill-snow
.ql-snow .ql-tooltip[data-mode=link]::before {
  content: "Enter link:";
}
.ql-snow .ql-tooltip[data-mode=formula]::before {
  content: "Enter formula:";
}
.ql-snow .ql-tooltip[data-mode=video]::before {
  content: "Enter video:";
}

改为


.ql-snow .ql-tooltip[data-mode=link]::before {
    content: "输入链接:" !important;
}
//.ql-snow .ql-tooltip[data-mode=formula]::before {
//    content: "Enter formula:";
//}
.ql-snow .ql-tooltip[data-mode=video]::before {
    content: "输入视频地址:" !important;
}



.ql-snow .ql-tooltip.ql-editing a.ql-action::after {
    border-right: 0px;
    content: 'Save';
    padding-right: 0px;
}

改为

.ql-snow .ql-tooltip.ql-editing a.ql-action::after {
    border-right: 0px;
    content: '保存' !important;
    padding-right: 0px;
}
