### ISSUE TITLE
IE11浏览器下用Windows10自带的输入法，会出现无法输入中文的情况

### ISSUE THREAD

**Issue by lan0909** [surmon-china/vue-quill-editor#153]
IE浏览器下，用Windows10自带的输入法：
1.会出现第一个字母自动出现在编辑器里，在第二行也会出现第一个字母。
![image](https://user-images.githubusercontent.com/30795369/35616965-ca31bf02-06b1-11e8-97ec-27dfa72dacd9.png)
2.正在输入的时候，光标会自动跳到前面去。
![image](https://user-images.githubusercontent.com/30795369/35617050-0a4fb026-06b2-11e8-8868-73d82b0c3bca.png)

QQ浏览器兼容模式下，用QQ输入法也会出现类似问题。

**Comment by surmon-china** [comment]
问题已知，quill 本身的问题。合并至 #56
