### ISSUE TITLE
请问link中填写的链接如何补充格式 如填写www.google.com将其转为https://www.google.com。现在我在quile的text-change中找到了修改link时候的状态，我应该怎样将输入的链接作无http链接的填充

### ISSUE THREAD

**Issue by jamesxieliang11** [surmon-china/vue-quill-editor#154]
### 中文用户注意：

1. 尽量用英文描述你的 issue
2. 不要把内容堆彻在标题上，逻辑清晰地写在内容区
3. 贴代码要提前格式化好，有颜色高亮那种，贴文本，不要贴图片
4. 提问题前，必须仔细阅读 REMADE.md + 在已关闭的问题中寻找与自身相关的问题，90% 的可能它已经被解决
5. **如果无法做到提一个合格、优秀的问题，则问题会被 close + block**

#### Reproduction Link
- A minimal JSBin, JSFiddle, Codepen, or a GitHub repository that can reproduce the bug.
- You could start with this template: https://jsfiddle.net/39epgLj0/

#### What is actually happening?

**Comment by surmon-china** [comment]
获取可以去发掘一下，quill 内部是否有读写拦截的 api。

**Comment by jamesxieliang11** [comment]
好的 在尝试了  谢谢
