### ISSUE TITLE
能不能添加行高，和设置字号是数字的方法？

### ISSUE THREAD

**Issue by maplehsu** [surmon-china/vue-quill-editor#157]
常用的功能这个两个功能必不可缺的，能否下次升级添加？

**Comment by surmon-china** [comment]
1. [ 组件 ] 是一个粘合剂，不参与任何对 Quill 的定制
2. 这个问题即便出现在 Quill 的 Issues 区域，得到的回答也会是利用已开放的强壮的 API 自定义。

所以，这一类的业务需求不会满足的。

**Comment by FuzzyFade** [comment]
nmsl

**Comment by FuzzyFade** [comment]
傻逼东西
