### ISSUE TITLE
严重bug！！

### ISSUE THREAD

**Issue by maplehsu** [surmon-china/vue-quill-editor#158]
在编辑器内容中间添加空格不生成&nbsp; 这个导致接口回传的时候 排版不一致

**Comment by surmon-china** [comment]
详细描述

**Comment by ChaselX** [comment]
quill渲染空格有用&nbsp吗？

**Comment by surmon-china** [comment]
首先，你要知道富文本的编辑器的工作原理，是基于 H5 DOM 接口的，不是 textarea 等别的东西，而 html 中无法识别多个空格，只有 &nbsp; 是可以被正常渲染为一个空格的，当你改变内容时，你的空格也必须是 nbsp; 所以！不要再反馈这些常识性问题了！

**Comment by ChaselX** [comment]
感觉主要还是不同富文本编辑器渲染机制的问题，之前试着用这个，但是发现没办法渲染成通用样式作为邮件模板。后来改用了CKEditor，缩进和空格的样式都会渲染成对应的原生html标签和样式。

**Comment by surmon-china** [comment]
quill 的样式靠 css class name 来输出，不同于内联样式；
渲染方面，确实是每个开源编辑器都不会一样，CKEditor 类似 [codemirror](https://surmon-china.github.io/vue-codemirror/)，如果你要实现一样的效果，或许可以通过某些 hack 来做到，目前我也发现可能是输出取值时存在问题，稍后测试。

**Comment by maplehsu** [comment]
感谢楼主回复，目前能想到的就是用正则，在你输出的地方 quill.pasteHTML(content)  里面添加正则表达式，除了需要的html标签以外，把所有的空格都替换成&nbsp; 但是目前这个问题正则比较麻烦还没有解决。现在这个问题很棘手。

**Comment by maplehsu** [comment]
因为之前没有测试过，所以空格不能生产&nbsp; 这个问题没有遇见，如果不生成&nbsp;的话 后台接口返回数据的时候，就没有&nbsp；导致页面回显格式不对

**Comment by surmon-china** [comment]
你完全可以在宿主组件维护一个 computed 属性啊，自定义 set get 就 ok 了，也没有那么麻烦

**Comment by surmon-china** [comment]
确定组件内部不会再做处理了，官方针对这个问题进行过多次回答，有特殊需求的话，外部处理。

https://github.com/quilljs/quill/issues/996#issuecomment-265242865

**Comment by maplehsu** [comment]
已经解决希望对大家有帮助
.ql-editor {
  white-space: normal!important;
}
改变编码格式即可

**Comment by 948198676** [comment]
.ql-editor {
white-space: normal!important;
}
使用这个空格会减半是怎么回事啊

**Comment by xiaohongzhou** [comment]
.ql-editor {
white-space: normal!important;
}
使用这个空格会减半怎么解决呢，求大神解答

**Comment by nanhang** [comment]
ql-container 中使用 pre-wrap
ql-editor 中使用 normal
.ql-container {
            white-space: pre-wrap !important;
            .ql-editor {
                white-space: normal !important;
            }
        }
在 v_html 中注意 pre-wrap 的使用

**Comment by ClarkWong** [comment]
> ql-container 中使用 pre-wrap // 解决空格减半问题
> ql-editor 中使用 normal // 解决多个空格合并的问题
> 
> ![image](https://user-images.githubusercontent.com/33409470/60698018-f8e3ec00-9f1f-11e9-8d3f-82e69b5efc51.png)
> 
> 导出的 html 使用时( v_html ) 需要注意 pre-wrap，注意设置 class="ql-editor"
> 其他问题可参考：https://www.yuque.com/u177061/skzsvt/tb2oih

牛批

**Comment by samyoo-zhang** [comment]
### A third-level heading
