### ISSUE TITLE
关于字体的问题/some question about font family

### ISSUE THREAD

**Issue by leopardzhang** [surmon-china/vue-quill-editor#162]
在设置字体的地方添加自己需要的宋体和微软雅黑之后为什么会出现在选择字体时 全都是sans serif的这种情况？

When I set the font Family('SimSong' and 'Microsoft Yahei') whcih I needed,then in the webPage when I want chose the font family I want there are all the sans serif!

**Comment by surmon-china** [comment]
善用搜索，#142
