### ISSUE TITLE
关于复制粘贴图片转base64的问题

### ISSUE THREAD

**Issue by liuyongwei0** [surmon-china/vue-quill-editor#165]
## 问题描述：
之前按照 [10秒带你实现图片上传到服务器#135](url) 所述的方法  ，实现了本地图片上传到自身服务器，但是一直在想本地图片如果直接复制不点击富文本上面的图片上传图标，复制进来的图片还是转成了base64，怎么拦截到这个操作然后转化成url插入到富文本中，困扰了很久，求推荐的方法，谢谢

**Comment by surmon-china** [comment]
注册 Quill 模块，监听键盘事件，或粘贴事件，然后做你要做的处理。
参考别的插件：
https://github.com/kensnyder/quill-image-drop-module
https://github.com/NextBoy/quill-image-extend-module
