### ISSUE TITLE
when quill-editor inited, change options no use

### ISSUE THREAD

**Issue by hu3402379** [surmon-china/vue-quill-editor#175]
#### Vue.js 2.3.2 and vue-quill-editor 3.0.5

the code like this:
```
<quill-editor v-model="desc" :options="editorOption"></quill-editor>

data() {
        return {
            editorOption: {
                readOnly: true
            }
        }
    },

```
if I click a button to change editorOption.readOnly = false, the component does not work.
my code likes this:
```
this.editorOption = Object.assign(this.editorOption, {
         readOnly: false
 })
```

why? thanks

**Comment by surmon-china** [comment]
`<quill-editor :disabled="false" />`

https://github.com/surmon-china/vue-quill-editor/blob/master/src/editor.vue#L52
https://github.com/surmon-china/vue-quill-editor/blob/master/src/editor.vue#L141
