### ISSUE TITLE
设置视频宽高

### ISSUE THREAD

**Issue by HeZai** [surmon-china/vue-quill-editor#186]
请问插入的视频可以设置它的宽高吗

**Comment by HeZai** [comment]
已找到插件[quill-blot-formatter](https://github.com/Fandom-OSS/quill-blot-formatter)

**Comment by Donng** [comment]
@HeZai  你好，想问一下视频上传是什么要求，我上传 mp4 url 就会自动下载视频。

**Comment by wuxiaolan91** [comment]
> @HeZai 你好，想问一下视频上传是什么要求，我上传 mp4 url 就会自动下载视频。

我和你相反, 上传 mp4 格式不会自动下载,但是上传 avi 格式会自动下载
