### ISSUE TITLE
默认高度怎么设置？

### ISSUE THREAD

**Issue by nickrogit** [surmon-china/vue-quill-editor#187]
初始化时不填默认内容，默认高度在哪里设置？editorOption参数对应的所有api文档在哪？

**Comment by surmon-china** [comment]
https://quilljs.com/docs/quickstart/

**Comment by iHelin** [comment]
文档里没找到啊

**Comment by surmon-china** [comment]
高度应该是需要通过 css 设置的

**Comment by user20161119** [comment]
@iHelin 找到解决办法了吗？我也找这个呢

**Comment by user20161119** [comment]
找到了，修改css height 
```
.ql-editor{
	height:400px;
}
```

**Comment by wingzzzz** [comment]
@user20161119 这个css样式只能设全局的才会生效，如果有两个editor需要不同的默认高度，这样设置会互相干扰，请问你怎么处理的？

**Comment by wingzzzz** [comment]
[http://asing1elife.com/vue/2017/12/07/vue-quill-editor-%E5%AF%8C%E6%96%87%E6%9C%AC%E6%A1%86%E7%BC%96%E8%BE%91%E5%99%A8/](url)

**Comment by pkwenda** [comment]
u can set content

```
<p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p>
```

**Comment by lizhengpei** [comment]
在 <quill-editor class="quillEditor" /> 添加一个 class类，然后 
<style lang="scss" scoped>
.quillEditor /deep/ .ql-editor {
  height: 400px;
}
</style>
即可解决 scoped  全局问题

**Comment by lizhengpei** [comment]
> 在 quill-editor 组件标签 添加一个 class类，然后
> 
> <style lang="scss" scoped> .quillEditor /deep/ .ql-editor { height: 400px; } </style>
> 即可解决 scoped 全局问题

**Comment by Baconcy** [comment]
怎么让富文本里面的英文全部变为汉字？
