### ISSUE TITLE
中文输入法，在最新chrome版本下会有问题

### ISSUE THREAD

**Issue by ReAlign** [surmon-china/vue-quill-editor#190]
前置：

1、最新chrome版本（具体版本号还在排查，65.0.x）
2、在行首
3、中文输入
现象：

1、行首第一个字符会被直接渲染成字母
2、单字母汉字，按空格，会被渲染成字母+空格

![](https://haitao.nos.netease.com/43801989-d4b7-4c55-87b5-2e77935154a8.gif)

**Comment by JefferyLiang** [comment]
A problem same here, in the live demo.

**Comment by ReAlign** [comment]
already solved，[issue](https://github.com/quilljs/quill/issues/2045)

**Comment by Ex-Caliburn** [comment]
希望作者尽快更新依赖库quill 升级到1.3.6 @Surmon

**Comment by surmon-china** [comment]
@Ex-Caliburn 所以你到底明白 package.json 中版本号前缀的含义吗

**Comment by Ex-Caliburn** [comment]
@surmon-china 以前以为是固定版本，原来是兼容旧版本 , 原因是我的项目不会自动更新依赖

**Comment by surmon-china** [comment]
你要手动重装啊大兄弟，无论我有没有手动更新那个版本号，npm 本来就是解决版本依赖管理的好吗
