### ISSUE TITLE
样式输出问题

### ISSUE THREAD

**Issue by Ben199011** [surmon-china/vue-quill-editor#191]
像这种的<p class="ql-align-center">f<span style="background-color: rgb(240, 102, 102);">设计费 </span></p>样式"ql-align-center"居中，编译代码段到别的页面，我还要写相应的样式表吗？有支持内联style的方法吗？就是把class="ql-align-center"改为style="text-align: center;"这种的

**Comment by LOWINC** [comment]
@Ben199011   问题解决了吗？

**Comment by weituotian** [comment]
怎么搞呢？

**Comment by typeofNaN** [comment]
请问大佬，如何将类名样式转为内联样式？有option  进行设置吗？谢谢！
