### ISSUE TITLE
[HELP] Import vue-quill-editor/dist/ssr in ssr Single File Components

### ISSUE THREAD

**Issue by serdydev** [surmon-china/vue-quill-editor#196]
#### Vue.js version and component version
"vue": "^2.5.15",
"vue-quill-editor": "^3.0.5"

#### Reproduction
Context :
- Vue in SSR (vue-hackernew)
- I try to import vue-quill-editor directly in a Single File Components

```
<template>
  <div class="comp-form-input form-group form-input">
    <label v-if="label" :for="name">{{ label }}</label>
    <small v-if="helperText">{{ helperText }}</small>
    <div class="inputContainer">
      <div
        :content="value"
        @change="handleInput($event)"
        v-quill:myQuillEditor="editorOptions"
      ></div>
      <small v-show="hasErrors" class="form-text invalid-feedback">{{ getErrorName }}</small>
    </div>
  </div>
</template>

<script>
  // Quill is used only in one component
  import { quillEditor } from 'vue-quill-editor/dist/ssr'

  export default {
    name: 'form-editor',
    directives: {
      quillEditor
    },
    props: {
      label: {
        type: String,
        required: false
      },
      name: {
        type: String,
        required: true
      },
      value: {
        type: String,
        default: ''
      },
      helperText: {
        type: String,
        required: false
      }
    },
    data() {
      return {
        editorOptions: {
          modules: {
            toolbar: [
              ['bold', 'italic', 'underline'],
              ['link'],
              [{ indent: '-1' }, { indent: '+1' }],
              [{ align: [] }]
            ]
          },
          theme: 'snow',
          placeholder: ''
        }
      }
    },
    inject: ['$validator'],
    methods: {
      handleInput(event) {
        this.$emit('input', event.html)
      }
    },
    computed: {
      hasErrors() {
        if (this.errors) {
          return this.errors.has(this.name)
        }
        return false
      },
      getErrorName() {
        if (this.errors) {
          return this.errors.first(this.name)
        }
        return false
      }
    }
  }
</script>

<style lang="css">
  @import '../../../node_modules/quill/dist/quill.snow.css';
</style>
```
#### Steps to reproduce
Import vue-quill-editor/dist/ssr in a component with a directive

#### What is Expected?
Quill is working		

#### What is actually happening?
Error 500 with this error message :
```
ReferenceError: document is not defined
    at Object.DIFF_DELETE (node_modules/quill/dist/quill.js:7588:0)
    at __webpack_require__ (node_modules/quill/dist/quill.js:36:0)
    at Object.defineProperty.value (node_modules/quill/dist/quill.js:980:0)
    at __webpack_require__ (node_modules/quill/dist/quill.js:36:0)
    at Object.defineProperty.value (node_modules/quill/dist/quill.js:5582:0)
    at __webpack_require__ (node_modules/quill/dist/quill.js:36:0)
    at Object.defineProperty.value (node_modules/quill/dist/quill.js:9972:0)
    at __webpack_require__ (node_modules/quill/dist/quill.js:36:0)
    at Object.<anonymous> (node_modules/quill/dist/quill.js:11484:0)
    at __webpack_require__ (node_modules/quill/dist/quill.js:36:0)
```

Hi,

I get a 500 when I try to import vue-quill-editor directly in a Single File Components and use the directive only in this component. 

It's working when I import vue-quill-editor/dist/ssr from app.js with Vue.use(), it's not working when I import it in the component.

I clearly dont understand something, maybe my syntax is not correct ?

I dont want to use vue-quill-editor from app.js/vue.use() because I want Webpack to bundle it only for one route, not in vendor.js (Quill is big)

Thanks for the good work,

and have a good day

Hugo

**Comment by surmon-china** [comment]
```javascript
import { quillEditor } from 'vue-quill-editor/dist/ssr'
```

`quillEditor` is a directive object, is not a component object.

```javascript
export default {
    name: 'form-editor',
    directives: {
        quill: quillEditor
    }
}
```

**Comment by serdydev** [comment]
Ouf! I forgot the "quill: " Sorry for that. 
Thanks again for the good work and the help

**Comment by serdydev** [comment]
Hi,

finally, I thought it worked, but it's only because I had the vue-quill declaration in my entry-server.

Is it working correctly in SSR mode ?

This is not working : 

`<template>
  <div class="comp-form-input form-group form-input">
    <label v-if="label" :for="name">{{ label }}</label>
    <small v-if="helperText">{{ helperText }}</small>
    <div class="inputContainer">
      <div
        :content="value"
        @change="handleInput($event)"
        **v-quill:myQuillEditor="editorOptions"**
      ></div>
      <small v-show="hasErrors" class="form-text invalid-feedback">{{ getErrorName }}</small>
    </div>
  </div>
</template>

<script>
  **import { quillEditor } from 'vue-quill-editor/dist/ssr'**

  export default {
    name: 'form-editor',
    **directives: {
      quill: quillEditor
    },**
    props: {
      label: {
        type: String,
        required: false
      },`

I get this error : 
`ReferenceError: document is not defined
    at Object.DIFF_DELETE (node_modules/quill/dist/quill.js:7588:0)
    at __webpack_require__ (node_modules/quill/dist/quill.js:36:0)
    at Object.defineProperty.value (node_modules/quill/dist/quill.js:980:0)
    at __webpack_require__ (node_modules/quill/dist/quill.js:36:0)
    at Object.defineProperty.value (node_modules/quill/dist/quill.js:5582:0)
    at __webpack_require__ (node_modules/quill/dist/quill.js:36:0)
    at Object.defineProperty.value (node_modules/quill/dist/quill.js:9972:0)
    at __webpack_require__ (node_modules/quill/dist/quill.js:36:0)
    at Object.<anonymous> (node_modules/quill/dist/quill.js:11484:0)
    at __webpack_require__ (node_modules/quill/dist/quill.js:36:0)`

**Comment by zajca** [comment]
This is not going to work. Quill ssr is not really ssr it's just directive which is inserted during ssr where it's require `document` and fail.
That's why is in Nuxt example `ssr: false`: https://github.com/surmon-china/vue-quill-editor/blob/master/examples/nuxt-ssr-example/nuxt.config.js#L4
