### ISSUE TITLE
How to disable autofocus when editor renders?

### ISSUE THREAD

**Issue by andgordio** [surmon-china/vue-quill-editor#201]
I have multiple quill editors on a page, and the page always scrolls down to the last non-empty one on load. I found a similar issue being currently discussed on our [neighbor's quill component GitHub](https://github.com/zenoamaro/react-quill/issues/317). Could [their solution](https://github.com/zenoamaro/react-quill/pull/321/files) be quick fix for vue-quill too?

**Comment by andgordio** [comment]
Discovered a pull request aimed at this issue. Looking forward to its merge!

**Comment by irshadahmedevs** [comment]
I explore this issue on many **forums** but nothing worked for me, but I fixed this in some other way with a **JS** "window" instance, use this "`window.scroll(0,0);`" method till a genuine fix.

**Comment by vZanchiV** [comment]
I do the same, but you see the window scroll with IE for example. It's crazy somebody had a soluce for fix this fucking bug

**Comment by Jaspur** [comment]
@surmon-china  please merge this

**Comment by binaryshrey** [comment]
@AkhonzadaIrshad Can you explain in detail how to use your fix.
It's been troubling me a lot

**Comment by jfaq89** [comment]
Same problem here. Any updates?

**Comment by felipebelluco** [comment]
Same problem here. Any updates?

**Comment by quroom** [comment]
I have spent a few hours.
But there is no solution.
The reason why autofocus happens, when the data is changed, automatically happens scroll to quilleditor.
So I made little tricky solution.
Just add disabled with data value.
And then when first change event, set quill_disabled data to false.
Then you can meet no-autofocus quill-editor after initialization at the first.
```
<quill-editor
  ref="myQuillEditor"
  :disabled="quill_disabled"
  @change="quill_disabled=false;"
/>
```

I hope you guys solve your problem.

**Comment by quroom** [comment]
Set initial data
```
quill_disabled = false
```
This will prevent autofocus, and when dom is updated, change the quill_disabled as true.
No more autofocus in eidtor render.

```
<template>
...
        <quill-editor
            ref="myQuillEditor"
            v-model="special_agreement"
            :options="editorOption"
            :disabled="quill_disabled"
          />
...
</template>
```

```
created(){
...
   this.$nextTick(()=>{
      this.quill_disabled=false;
    })
}
```

**Comment by baxa29102001** [comment]
> 

Thanks bro very much

**Comment by quroom** [comment]
> > 
> 
> Thanks bro very much

You're welcome!
