### ISSUE TITLE
Indented lists are not outputting as such 

### ISSUE THREAD

**Issue by arliber** [surmon-china/vue-quill-editor#208]
#### Vue.js version and component version
Latest versions of vue-quill-editor and Vue

#### Reproduction Link
[https://surmon-china.github.io/vue-quill-editor/](https://surmon-china.github.io/vue-quill-editor/)

#### Steps to reproduce
Reproducible in the official examples page (example #2)
Just create an ordered list with some hierarchy (indented items)

#### What is Expected?		
When creating nested lists - I would expect that the parent `<li>` will contain an `<ol>` or `<ul>` so that the bullets are actually changing when the resulting HTML is presented.

#### What is actually happening?
The HTML output looks like that:
```javascript
<ol>
    <li><span class="ql-font-serif">Parent</span></li>
    <li class="ql-indent-1">child 1</li>
    <li class="ql-indent-1"><span class="ql-font-serif">child 2</span></li>
</ol>
```

I can use CSS to indent the child elements but they are still enumerated 2 and 3 while I would expect them to be enumerated like (i) and (ii) or similar.

**Comment by mubashiralisiddiqui** [comment]
I am having the same issue any solution for that?

**Comment by zhaohuangyan** [comment]
请问解决了吗

**Comment by zhaohuangyan** [comment]
I am having the same issue any solution for that?
