### ISSUE TITLE
大量图片base64储存问题

### ISSUE THREAD

**Issue by cshhs** [surmon-china/vue-quill-editor#21]
是否可以图片上传获取url，然后设置图片的显示。而不是直接使用base64，这样后端可能储存会有大量的数据。

**Comment by SkyFire-Lee** [comment]
本人也有这问题,本人利用 #7 的实例代码,添加一个upload的按钮
```
        <div id="toolbar">
            <input type="file" @change='upload' style='display: none !important;'>
            <!-- Add font size dropdown -->
            <select class="ql-size">
                <option value="small"></option>
                <!-- Note a missing, thus falsy value, is used to reset to default -->
                <option selected></option>
                <option value="large"></option>
                <option value="huge"></option>
            </select>
            <!-- Add a bold button -->
            <button class="ql-bold"></button>
            <!-- Add subscript and superscript buttons -->
            <button class="ql-script" value="sub"></button>
            <button class="ql-script" value="super"></button>
            <button @click="upclick"><i class="el-icon-upload"></i></button>
        </div>
```
然后,利用`upclick`的去触发`input[type=file]`的`click`事件,去调用七牛的上传,我是利用`qiniu-web-uploader`插件进行上传,然后得到上传的`url`添加至富文本内容中即可.

**Comment by surmon-china** [comment]
@SkyFire-Lee 是否有实例代码，可以参考下吗？

**Comment by SkyFire-Lee** [comment]
@surmon-china 要配合后端生成token,然后传给js进行上传,因为七牛的token生成有些麻烦,就简单写了一下,[https://github.com/SkyFire-Lee/vue-qiniu-upload-demo](https://github.com/SkyFire-Lee/vue-qiniu-upload-demo),是基础代码,希望对你的项目有帮助

**Comment by surmon-china** [comment]
@SkyFire-Lee Tks:)

**Comment by ljyf5593** [comment]
编辑器原生是支持插入图片回调函数的，但是不知为何，在vue下引用时回调函数无效，参考 https://github.com/quilljs/quill/pull/995

**Comment by zuijiaoluo** [comment]
@surmon-china 这个可以直接把图片上传到后端吗？现在是用base64，做个开关可好？

**Comment by surmon-china** [comment]
@zuijiaoluo 正确的做法是使用quill的第三方扩展库（上传扩展插件），去实现上传需求

**Comment by surmon-china** [comment]
问题合并 #7 #23

**Comment by zuijiaoluo** [comment]
@surmon-china 我要怎么吧第三发组件组册到这个模块呢？在vue中

**Comment by surmon-china** [comment]
稍等，今天版本更新后，你将可以看到示例代码。

**Comment by www295686243** [comment]
@surmon-china 请问图片上传的第三方组建 示例代码在哪?

**Comment by surmon-china** [comment]
@www295686243 https://github.com/surmon-china/vue-quill-editor/blob/master/examples/03-example.vue#L34 自行开发

**Comment by 1008611** [comment]
i used the  customButtonClick to upload pictures(change the base64 to imgurl ) . i  can get the img url but  can not insert  the image url in content.

**Comment by EonchGao** [comment]
这种地址展示的方法，如何使图片实现自由调整大小位置功能？
