### ISSUE TITLE
引入样式文件，但样式依然不生效，如何解决？

### ISSUE THREAD

**Issue by Uhaiping** [surmon-china/vue-quill-editor#235]
我在main.js中引入了那三个样式文件，但是编辑器中文字样式有效，发布后样式就无效了
main.js:
import 'quill/dist/quill.core.css'
import 'quill/dist/quill.snow.css'
import 'quill/dist/quill.bubble.css'
使用的地方：
<quill-editor v-model="newsForm.content"></quill-editor>
下面涉及ql开头的class并没有读取到
![image](https://user-images.githubusercontent.com/33239901/41446919-f84ce29e-7084-11e8-992d-874c87337e84.png)

**Comment by Uhaiping** [comment]
使用的地方：<quill-editor v-model="newsForm.content"></quill-editor>

**Comment by Uhaiping** [comment]
`<quill-editor v-model="newsForm.content"></quill-editor>`

**Comment by xian107** [comment]
我也遇到这个问题？怎么解决的？

**Comment by pkwenda** [comment]
需要定义在
```
    <div class="output ql-snow">
      <div class="ql-editor" v-html="content"></div>
    </div>

```

可以看这个 demo
