### ISSUE TITLE
上传的图片，为什么不能改变大小?

### ISSUE THREAD

**Issue by heshan-song** [surmon-china/vue-quill-editor#26]
上传后的图片，无法改变大小，如何解决呢？

**Comment by surmon-china** [comment]
建议通过quill的第三方扩展库角度去解决，组件不包含quill内部功能的具体实现。

**Comment by surmon-china** [comment]
参考这里：
https://github.com/surmon-china/vue-quill-editor/blob/master/examples/04-example.vue

**Comment by chending1994** [comment]
可拉伸怎么实现啊。。。

**Comment by jinweibin** [comment]
> ![image](https://user-images.githubusercontent.com/14355994/47336198-4174b580-d6c1-11e8-97cf-e8b732d564c5.png)
> 只要引入就报错

你解决了这问题了吗
