### ISSUE TITLE
默认传入的html无样式

### ISSUE THREAD

**Issue by sunchenguang** [surmon-china/vue-quill-editor#283]
默认content为
```
 content: '<p style="color: rgb(230, 0, 0);">testtest</p>',
或
 content: '<div style="color: rgb(230, 0, 0);">testtest</div>',
```
前一种渲染出来没样式，后一种渲染出来变成了p标签，也没样式。

这很不科学啊。连内联样式都不支持。
导致从别的种类的富文本拷贝过来的html同步过来无法复原展示（没样式，有内容）

**Comment by will007008** [comment]
同样的问题

**Comment by gengzhaoji** [comment]
请问解决了么

**Comment by qianniandefeng** [comment]
同问

**Comment by sunchenguang** [comment]
未解决。

**Comment by wsosop** [comment]
请问下，现在解决了吗

**Comment by gengzhaoji** [comment]
解决了，涉及到源码了，最后项目也有别的要求也换了个编辑器，谢谢了




------------------ 原始邮件 ------------------
发件人: "wsosop"<notifications@github.com>;
发送时间: 2019年4月12日(星期五) 下午3:38
收件人: "surmon-china/vue-quill-editor"<vue-quill-editor@noreply.github.com>;
抄送: "忆梦"<1317993594@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [surmon-china/vue-quill-editor] 默认传入的html无样式 (#283)




请问下，现在解决了吗
