### ISSUE TITLE
Object.assign	IE Not compatible

### ISSUE THREAD

**Issue by zhouhaijun** [surmon-china/vue-quill-editor#30]
Object.assign	IE Not compatible

**Comment by surmon-china** [comment]
Quill official statement does not support IE11 the following browser.

https://github.com/quilljs/quill/issues/936

**Comment by zhouhaijun** [comment]
Edge

**Comment by surmon-china** [comment]
I will hotfix this right now.

**Comment by surmon-china** [comment]
I fixed this in v2.0.2, just update your dependency and it should work :) !
