### ISSUE TITLE
No sync between the :content and the data

### ISSUE THREAD

**Issue by ramakrishnamundru** [surmon-china/vue-quill-editor#32]
It is a bug

### BUG REPORT TEMPLATE
when we enter text in editor it is not reflected in the data attached to :content

#### Reproduction Link
- A minimal JSBin, JSFiddle, Codepen, or a GitHub repository that can reproduce the bug.
@PeterKnight repo
https://github.com/PeterKnight/quilltest

#### Steps to reproduce
same steps as his.
after opening the app, add ```<div v-text="content"></div>``` after his code, then in app clear the editor untill you see the placeholder and enter text again.
#### What is Expected?		
The change in editor should reflect in the div below.
#### What is actually happening?
no change in the div with v-text
in my situation it is not working from the start.
The content changes if we change the content using v-model with an input, but the reverse is not happening

**Comment by surmon-china** [comment]
I will be testing, can you post your detailed example code?

**Comment by ramakrishnamundru** [comment]
Hi,
I have made a repo reproducing this issue 
https://github.com/ramakrishnamundru/quill-issue

steps:
`npm install` or `yarn`
`npm run hot`
open http://localhost:8080/
Try editing the text in editor, the changes are not reflected in the data,
But editing the input changes data in editor.

**Comment by surmon-china** [comment]
Yes, i saw your issues code, it is in the expected working state, `: content` is a one-way data binding on the editor, it only accepts the input value, its internal changes will pass` Change` and `input` events are distributed. When using`: content`, you need to manually monitor the changes in the data, as in the following code:

```vue
<quill-editor :content="content" 
                          :options="quilleditorOption" 
                          ref="myTextEditor" 
                          @change="onEditorChange($event)"></quill-editor>

<script>
import Vue from 'vue';
import VueQuillEditor from 'vue-quill-editor';
Vue.use(VueQuillEditor);
export default {
    data() {
        return {
            content: '<h1>Vue quill Editor</h1>',
            quilleditorOption: {
                // some quill options
            }
        }
    },
    methods: {
        onEditorChange({ editor, html, text }) {
            console.log({ editor, html, text })
            this.content = html
        }
    }
}
</script>

```

Or use `v-model` for two-way data binding,` v-model` internal is the listening `input` event, so it can automatically respond.

Is this the answer you want?

**Comment by ramakrishnamundru** [comment]
I thought of using this, but I thought the `:content` is two-way data binding like v-model, that's why I posted the issue.
Anyway great work.
