### ISSUE TITLE
Please build and publish this package, instead of including an not-compiled .vue.

### ISSUE THREAD

**Issue by laosb** [surmon-china/vue-quill-editor#33]
This way this package can be used in non-webpack apps.

**Comment by surmon-china** [comment]
@laosb You can try to use, compile for the first time, do not know if it can run.

https://github.com/surmon-china/vue-quill-editor/blob/master/dist/index.js

**Comment by laosb** [comment]
Will try in Meteor when time is with me. Thx!

**Comment by surmon-china** [comment]
The problem is temporarily closed, if the problem is reproduced, please reopen it.
