### ISSUE TITLE
在使用v-model双向绑定编辑器时输入失焦

### ISSUE THREAD

**Issue by TheBlueSkim** [surmon-china/vue-quill-editor#334]
如题，在使用v-model进行双向绑定的时候，每次输入都会导致编辑器失焦，不用v-model则没有这个问题

`<quill-editor
                  v-model="form.content"
                  :options="editor_option"
                ></quill-editor>`

**Comment by mastergandalf** [comment]
如果在当前页面引用了1个以上的编辑器，且v-model 都指向同一个值，就会每次输入都会失焦

**Comment by benben994** [comment]
Anyway to solve this?

**Comment by TheBlueSkim** [comment]
@benben994  I'm so sorry for not use github frequently, I had renounced the use of v-model and used @change like this
`<quill-editor
            :content="content"
            :options="editor_option"
            @change="setContent($event)"
          ></quill-editor>
`

**Comment by WuXianShi** [comment]
> @ benben994 我很抱歉不经常使用github，我放弃了使用v-model并像这样使用@change
> `<quill-editor :content="content" :options="editor_option" @change="setContent($event)" ></quill-editor> `

你好，现在用这种方式似乎也会出现失焦的情况耶，请问还有其他办法吗？
