### ISSUE TITLE
Unable to get custom image handler to work

### ISSUE THREAD

**Issue by RonWaller** [surmon-china/vue-quill-editor#340]
Having difficulty getting custom handler to work. I am probably not setting it up correctly.

#### Vue.js version and component version
Vue 2.6.10
component version ?
#### Reproduction Link
```html
<template>
  <div class="addBlog">
    <h1>Add New Blog</h1>
    <quill-editor v-model="content" :options="editorOptions" ref="myQuillEditor"/>
  </div>
</template>
```
```javascript
<script>
import 'quill/dist/quill.snow.css';
import { Quill, quillEditor } from 'vue-quill-editor';

export default {
  name: 'AddBlog',
  components: {
    quillEditor
  },
  data: () => ({
    title: '',
    category: '',
    content: '',
    editorOptions: {
      theme: 'snow',
      debug: 'info',
      placeholder: 'Type your post...',
      readOnly: true,
      modules: {
        toolbar: {
          container: [
            ['bold', 'italic', 'underline', 'strike'],
            ['link', 'image', 'video']
          ],
          handlers: { image: showImageUI }
        }
      }
    },
    // debug: 'info',
    // placeholder: 'Type your post...',
    // readOnly: true,
    // theme: 'snow'
    // },
    delta: undefined
  }),
  methods: {
    showImageUI() {
      alert('Image UI');
    }
  },
  watch: {
    content() {
      this.delta = this.$refs.myQuillEditor.quill.getContents();
    }
  }
};
</script>
```
#### What is Expected?	
For image button to execute custom handler and not run default action	

#### What is actually happening?
Error in data(): "ReferenceError: showImageUI is not defined"

###Edit:
Editor doesn't render, but removing the handler fixes that issue.

**Comment by RonWaller** [comment]
Well I discovered something very interesting with this issue. I was trying to implement this in Vue Js component but wasn't working. As a test I create a vanilla JS file and used the Quill quick start guide and would you believe it....it worked just like I was hoping. Now I just need to insert it into my Vue project.

**Comment by yehey1999** [comment]
> Well I discovered something very interesting with this issue. I was trying to implement this in Vue Js component but wasn't working. As a test I create a vanilla JS file and used the Quill quick start guide and would you believe it....it worked just like I was hoping. Now I just need to insert it into my Vue project.

May I know 

> Well I discovered something very interesting with this issue. I was trying to implement this in Vue Js component but wasn't working. As a test I create a vanilla JS file and used the Quill quick start guide and would you believe it....it worked just like I was hoping. Now I just need to insert it into my Vue project.

May I know how did you insert it in your project?

Thanks..

**Comment by yehey1999** [comment]
> Well I discovered something very interesting with this issue. I was trying to implement this in Vue Js component but wasn't working. As a test I create a vanilla JS file and used the Quill quick start guide and would you believe it....it worked just like I was hoping. Now I just need to insert it into my Vue project.

@RonWaller May I know did you insert it in vue project?

Thanks...
