### ISSUE TITLE
Cannot delete content by backspace key

### ISSUE THREAD

**Issue by zhazhacai** [surmon-china/vue-quill-editor#347]
I don't know why Google and IE can't delete content from behind, but Firefox can.Oddly enough, cursors can be deleted after the first text

**Comment by zhazhacai** [comment]
The reason for this is that the keyboard fallback mechanism is disabled in the project and has nothing to do with components.

**Comment by liwen327** [comment]
最后你是怎么解决的？

**Comment by Via1877** [comment]
请问解决了吗 @liwen327
