### ISSUE TITLE
如何阻止粘贴 base64图片

### ISSUE THREAD

**Issue by leiminghai** [surmon-china/vue-quill-editor#364]
自己做了粘贴的图片上传，并且成功的显示到了 富文本编辑器中
但是 插入返回URl的图片后  仍然插入了原来的base64图片
如何操作阻止base64图片的显示
用阻止默认事件烨不管用
![image](https://user-images.githubusercontent.com/23730545/67472207-59d83100-f683-11e9-9922-a46d201eac41.png)
![image](https://user-images.githubusercontent.com/23730545/67472408-a1f75380-f683-11e9-86d6-e181c842981b.png)

**Comment by xupeihong** [comment]
我也遇到这个问题，你解决了吗？

**Comment by stick777** [comment]
解决了,粘贴的时候判断下是图片就阻止默认的事件,用上传服务器的方法

**Comment by leiminghai** [comment]
![image](https://user-images.githubusercontent.com/23730545/84017494-55158280-a9b1-11ea-95e2-165b700fba4e.png)
![image](https://user-images.githubusercontent.com/23730545/84017569-6eb6ca00-a9b1-11ea-8431-f4054c5522bd.png)
![image](https://user-images.githubusercontent.com/23730545/84017660-90b04c80-a9b1-11ea-8b3c-eea5378e680a.png)
关键代码 这是我的处理方式

**Comment by leiminghai** [comment]
<quill-editor
      v-model="currentQuillData"
      :ref="configData.quillRef"
      placeholder="请输入评论内容"
      :options="configData.editorOption"
      @paste.native.stop="imagePaste"
      :class="{'limitHeight': configData.maxHeight, 'limitWidth': configData.maxWidth}"
    ></quill-editor>

**Comment by leiminghai** [comment]
<quill-editor
      v-model="currentQuillData"
      :ref="configData.quillRef"
      placeholder="请输入评论内容"
      :options="configData.editorOption"
      @paste.native.stop="imagePaste"
      :class="{'limitHeight': configData.maxHeight, 'limitWidth': configData.maxWidth}"
    ></quill-editor> 
/**
     * 图片粘贴处理
     * @param event
     */
    imagePaste(event) {
      console.log(event,'event')
        var items = event.clipboardData && event.clipboardData.items;
        var file = null;
        if (items && items.length) {
          // 检索剪切板items
          for (var i = 0; i < items.length; i++) {
            if (items[i].type.indexOf("image") !== -1) {
              file = items[i].getAsFile();
              break;
            }
          }
        }
        if (file) {
          this.uploadImage(file, true);
        } }
/**
     * 图片上传
     */
    uploadImage(data, isPaste) {
      let formData = new FormData();
      formData.append("upfile", data.file || data)
      let params = {
        action: "uploadimage",
        target: this.configData.type
      };

      upload
        .image(formData, params)
        .then(res => {
          let quill = this.$refs[this.configData.quillRef].quill;
          // 获取光标所在位置
          let length = quill.getSelection().index;
          if (isPaste) {
          }
          // 插入图片  res.info为服务器返回的图片地址
          quill.insertEmbed(length, "image", res.url);
          // 调整光标到最后
          quill.setSelection(length + 1);
        })
        .catch(err => {
          this.$message.error("图片插入失败");
        });
    },  
关键代码 这是我的处理方式 可以参考

**Comment by stick777** [comment]
/**
     * @description 粘贴
     * @param e
     */
  async pasteHandle (e) {
    QuillWatch.emit(this.quill.id, 0)
    let clipboardData = e.clipboardData
    let i = 0
    let items, item, types

    if (clipboardData) {
      items = clipboardData.items
      if (!items) {
        return
      }
      item = items[0]
      types = clipboardData.types || []

      for (; i < types.length; i++) {
        if (types[i] === 'Files') {
          item = items[i]
          break
        }
      }
      if (item && item.kind === 'file' && item.type.match(/^image\//i)) {
        e.preventDefault()
        this.file = item.getAsFile()
        let self = this
        // 如果图片限制大小
        if (self.config.size && self.file.size >= self.config.size * 1024 * 1024) {
          if (self.config.sizeError) {
            self.config.sizeError()
          }
        }
        await this.uploadImg()
        /* if (this.config.action) {
          this.uploadImg()
        } else {
          // this.toBase64()
        } */
      }
    }
  }
