### ISSUE TITLE
Can't not important.

### ISSUE THREAD

**Issue by RexHung0302** [surmon-china/vue-quill-editor#370]
引入相關套件後會崩壞，沒有印入相關套件時卻又能正常運行。
https://imgur.com/a/4hbEpJV
不曉得有沒有人碰到這問題。

關於 vue.config.js 的設定也打了。
```
configureWebpack: {
        plugins: [
            new webpack.ProvidePlugin({
                'window.Quill': 'quill/dist/quill.js',
                'Quill': 'quill/dist/quill.js'
            }),
        ],
        optimization: {
            splitChunks: {
                minSize: 20000,
                maxSize: 300000,
            }
        },
    },
```

引入時的語法

```
import hljs from 'highlight.js';
import { quillEditor } from 'vue-quill-editor';
import Quill from 'quill';
import ImageResize from '@taoqf/quill-image-resize-module';
import { ImageDrop } from 'quill-image-drop-module';
import QuillEmoji from 'quill-emoji';

Quill.register({
  'modules/imageResize': ImageResize,
  'modules/imageDrop': ImageDrop,
  'formats/emoji': QuillEmoji.EmojiBlot,
  'modules/emoji-shortname': QuillEmoji.ShortNameEmoji,
  'modules/emoji-toolbar': QuillEmoji.ToolbarEmoji,
  'modules/emoji-textarea': QuillEmoji.TextAreaEmoji
});
```

data 裡的使用打法如下

```
data() {
    return {
      content: '',
      editorOption: {
        modules: {
          imageDrop: true,
          imageResize: true,
          toolbar: {
            container: [
              ['bold', 'italic', 'underline', 'strike'], // 粗體、斜體、底線、刪除線
              ['emoji'], // 表情
              ['blockquote', 'code-block'], // block 區塊、code 區塊

              [{'header': 1}, {'header': 2}], // custom button values
              [{'list': 'ordered'}, {'list': 'bullet'}], // 數字列表、點列表
              [{'script': 'sub'}, {'script': 'super'}], // superscript/subscript
              [{'indent': '-1'}, {'indent': '+1'}], // 向內縮排/向外縮排
              [{'direction': 'rtl'}], // text direction

              [{'size': ['small', false, 'large', 'huge']}], // 字體大小
              [{'header': [1, 2, 3, 4, 5, 6, false]}], // h1~h6

              [{'color': []}], // 文字顏色、背景顏色
              [{'background': []}], // 背景顏色
              [{'font': []}], // 字體
              [{'align': []}], // 排列
              ['link', 'image', 'video'], // 插入超連結、插入圖片、插入影片
            ],
          },
          'emoji-toolbar': true,
          'emoji-textarea': true,
          'emoji-shortname': true,
        },
      },
    };
  },
```

希望能獲的解答了 非常感謝～

**Comment by finebo** [comment]
你是否解决了这个问题

Have you solved the problem

**Comment by RexHung0302** [comment]
已經解決了  給您看一下配置 我有把編輯器另外拉出來當一個 component

另外我有引入 quillRedefine 套件，是另外一位大大寫的，目的是為了上傳圖片直接拿到網址，而非data base 64，如果不需要可以把 created 內容全部移除，然後 data 裡的 editorOption 註解可以拿掉，quillRedefine 這個 component 可以不用註冊，相關的 code 都可以移除掉。

圖片上傳套件相關說明在此：[vue-quill-editor-upload](https://github.com/NextBoy/vue-quill-editor-upload)

```html
<template lang="pug">
  quill-editor(
    v-model='content', 
    ref="quillEditor", 
    :options='editorOption', 
    @blur='onEditorBlur($event)', 
    @focus='onEditorFocus($event)', 
    @ready='onEditorReady($event)',
    @change="onEditorChange($event)"
  )
</template>
```
```javascript
<script lang="js">
import {quillRedefine} from 'vue-quill-editor-upload';
import { quillEditor } from 'vue-quill-editor';
import Quill from 'quill';
import ImageResize from '@taoqf/quill-image-resize-module';
import { ImageDrop } from 'quill-image-drop-module';
import QuillEmoji from 'quill-emoji';


Quill.register({
  'modules/imageResize': ImageResize,
  'modules/imageDrop': ImageDrop,
  'formats/emoji': QuillEmoji.EmojiBlot,
  'modules/emoji-shortname': QuillEmoji.ShortNameEmoji,
  'modules/emoji-toolbar': QuillEmoji.ToolbarEmoji,
  'modules/emoji-textarea': QuillEmoji.TextAreaEmoji
});

export default {
  name: 'quill',
  components: {
    quillRedefine,
    quillEditor,
  },
  data() {
    return {
      content: '',
      editorOption: {
        // modules: {
        //   imageDrop: true,
        //   imageResize: true,
        //   toolbar: {
        //     container: [
        //       ['bold', 'italic', 'underline', 'strike'], // 粗體、斜體、底線、刪除線
        //       ['emoji'], // 表情
        //       ['blockquote', 'code-block'], // block 區塊、code 區塊

        //       [{'header': 1}, {'header': 2}], // custom button values
        //       [{'list': 'ordered'}, {'list': 'bullet'}], // 數字列表、點列表
        //       [{'script': 'sub'}, {'script': 'super'}], // superscript/subscript
        //       [{'indent': '-1'}, {'indent': '+1'}], // 向內縮排/向外縮排
        //       [{'direction': 'rtl'}], // text direction

        //       [{'size': ['small', false, 'large', 'huge']}], // 字體大小
        //       [{'header': [1, 2, 3, 4, 5, 6, false]}], // h1~h6

        //       [{'color': []}], // 文字顏色、背景顏色
        //       [{'background': []}], // 背景顏色
        //       [{'font': []}], // 字體
        //       [{'align': []}], // 排列
        //       ['link', 'image', 'video'], // 插入超連結、插入圖片、插入影片
        //     ],
        //   },
        //   'emoji-toolbar': true,
        //   'emoji-textarea': true,
        //   'emoji-shortname': true,
        // },
      },
    };
  },
  created(){
    let vm = this;
    this.editorOption = quillRedefine(
      {
        // 图片上传的设置
        uploadConfig: {
          action:  `你的後端API路由`,  // 必填参数 图片上传地址
          // 必选参数  res是一个函数，函数接收的response为上传成功时服务器返回的数据
          // 你必须把返回的数据中所包含的图片地址 return 回去
          res: (respnse) => {
            // 這邊填寫上傳完圖片要做的事
            return url;  // 这里切记要return回你的图片地址
          },
          methods: 'POST',  // 可选参数 图片上传方式  默认为post
          token: '你的token',  // 可选参数 如果需要token验证，假设你的token有存放在sessionStorage
          name: 'img',  // 可选参数 文件的参数名 默认为img
          size: 1024,  // 可选参数   图片限制大小，单位为Kb, 1M = 1024Kb
          accept: 'image/png, image/gif, image/jpeg, image/bmp, image/x-icon',  // 可选参数 可上传的图片格式
          // input点击事件  formData是提交的表单实体
          change: (formData) => { 
            // console.log('formData', formData);
          },
          // 设置请求头 xhr: 异步请求， formData: 表单对象
          header: (xhr, formData) => {
              // 有設定 header 可填
          },
          // start: function (){}
          start: (e) => {
            // console.log(e);
          },  // 可选参数 接收一个函数 开始上传数据时会触发
          end: (e) => {
            // console.log(e);
          },  // 可选参数 接收一个函数 上传数据完成（成功或者失败）时会触发
          success: (e) => {
            // console.log(e);
          },  // 可选参数 接收一个函数 上传数据成功时会触发
          error: (e) => {
            // console.log(e);
          }  // 可选参数 接收一个函数 上传数据中断时会触发
        },
         // 以下所有设置都和vue-quill-editor本身所对应
        placeholder: 'Write something...',  // 可选参数 富文本框内的提示语
        // theme: '',  // 可选参数 富文本编辑器的风格
        // toolOptions: null,  // 可选参数  选择工具栏的需要哪些功能  默认是全部
        // handlers: {}  // 可选参数 重定义的事件，比如link等事件
      }
    )
    //  console.log(this.editorOption)
  },
  methods: {
    onEditorBlur(quill) {
      
    },
    onEditorFocus(quill) {

    },
    onEditorReady(quill) {

    },
    onEditorChange(e){
      // console.log(e);
    },
    // onEditorChange({ quill, html, text }) {
    //   console.log('editor change!', quill, html, text);
    //   this.content = html;
    // },
  },
  computed: {

  },
  mounted() {

  },
};
</script>
```
```css
<style lang="scss">
  .ql-editor {
    height: 300px !important;
  }
  .quill-code {
    border: none;
    height: auto;
    > code {
      width: 100%;
      margin: 0;
      padding: 1rem;
      border: 1px solid #ccc;
      border-top: none;
      border-radius: 0;
      height: 10rem;
      overflow-y: auto;
      resize: vertical;
    }
  }
</style>
```

**Comment by finebo** [comment]
Thank you very much for your help. Now I cannot achieve the effect when introducing quill-emoji, could you please help me in this area

> 已經解決了 給您看一下配置 我有把編輯器另外拉出來當一個 component
> 
> 另外我有引入 quillRedefine 套件，是另外一位大大寫的，目的是為了上傳圖片直接拿到網址，而非data base 64，如果不需要可以把 created 內容全部移除，然後 data 裡的 editorOption 註解可以拿掉，quillRedefine 這個 component 可以不用註冊，相關的 code 都可以移除掉。
> 
> 圖片上傳套件相關說明在此：[vue-quill-editor-upload](https://github.com/NextBoy/vue-quill-editor-upload)
> 
> ```
> <template lang="pug">
>   quill-editor(
>     v-model='content', 
>     ref="quillEditor", 
>     :options='editorOption', 
>     @blur='onEditorBlur($event)', 
>     @focus='onEditorFocus($event)', 
>     @ready='onEditorReady($event)',
>     @change="onEditorChange($event)"
>   )
> </template>
> ```
> 
> ```js
> <script lang="js">
> import {quillRedefine} from 'vue-quill-editor-upload';
> import { quillEditor } from 'vue-quill-editor';
> import Quill from 'quill';
> import ImageResize from '@taoqf/quill-image-resize-module';
> import { ImageDrop } from 'quill-image-drop-module';
> import QuillEmoji from 'quill-emoji';
> 
> 
> Quill.register({
>   'modules/imageResize': ImageResize,
>   'modules/imageDrop': ImageDrop,
>   'formats/emoji': QuillEmoji.EmojiBlot,
>   'modules/emoji-shortname': QuillEmoji.ShortNameEmoji,
>   'modules/emoji-toolbar': QuillEmoji.ToolbarEmoji,
>   'modules/emoji-textarea': QuillEmoji.TextAreaEmoji
> });
> 
> export default {
>   name: 'quill',
>   components: {
>     quillRedefine,
>     quillEditor,
>   },
>   data() {
>     return {
>       content: '',
>       editorOption: {
>         // modules: {
>         //   imageDrop: true,
>         //   imageResize: true,
>         //   toolbar: {
>         //     container: [
>         //       ['bold', 'italic', 'underline', 'strike'], // 粗體、斜體、底線、刪除線
>         //       ['emoji'], // 表情
>         //       ['blockquote', 'code-block'], // block 區塊、code 區塊
> 
>         //       [{'header': 1}, {'header': 2}], // custom button values
>         //       [{'list': 'ordered'}, {'list': 'bullet'}], // 數字列表、點列表
>         //       [{'script': 'sub'}, {'script': 'super'}], // superscript/subscript
>         //       [{'indent': '-1'}, {'indent': '+1'}], // 向內縮排/向外縮排
>         //       [{'direction': 'rtl'}], // text direction
> 
>         //       [{'size': ['small', false, 'large', 'huge']}], // 字體大小
>         //       [{'header': [1, 2, 3, 4, 5, 6, false]}], // h1~h6
> 
>         //       [{'color': []}], // 文字顏色、背景顏色
>         //       [{'background': []}], // 背景顏色
>         //       [{'font': []}], // 字體
>         //       [{'align': []}], // 排列
>         //       ['link', 'image', 'video'], // 插入超連結、插入圖片、插入影片
>         //     ],
>         //   },
>         //   'emoji-toolbar': true,
>         //   'emoji-textarea': true,
>         //   'emoji-shortname': true,
>         // },
>       },
>     };
>   },
>   created(){
>     let vm = this;
>     this.editorOption = quillRedefine(
>       {
>         // 图片上传的设置
>         uploadConfig: {
>           action:  `你的後端API路由`,  // 必填参数 图片上传地址
>           // 必选参数  res是一个函数，函数接收的response为上传成功时服务器返回的数据
>           // 你必须把返回的数据中所包含的图片地址 return 回去
>           res: (respnse) => {
>             // 這邊填寫上傳完圖片要做的事
>             return url;  // 这里切记要return回你的图片地址
>           },
>           methods: 'POST',  // 可选参数 图片上传方式  默认为post
>           token: '你的token',  // 可选参数 如果需要token验证，假设你的token有存放在sessionStorage
>           name: 'img',  // 可选参数 文件的参数名 默认为img
>           size: 1024,  // 可选参数   图片限制大小，单位为Kb, 1M = 1024Kb
>           accept: 'image/png, image/gif, image/jpeg, image/bmp, image/x-icon',  // 可选参数 可上传的图片格式
>           // input点击事件  formData是提交的表单实体
>           change: (formData) => { 
>             // console.log('formData', formData);
>           },
>           // 设置请求头 xhr: 异步请求， formData: 表单对象
>           header: (xhr, formData) => {
>               // 有設定 header 可填
>           },
>           // start: function (){}
>           start: (e) => {
>             // console.log(e);
>           },  // 可选参数 接收一个函数 开始上传数据时会触发
>           end: (e) => {
>             // console.log(e);
>           },  // 可选参数 接收一个函数 上传数据完成（成功或者失败）时会触发
>           success: (e) => {
>             // console.log(e);
>           },  // 可选参数 接收一个函数 上传数据成功时会触发
>           error: (e) => {
>             // console.log(e);
>           }  // 可选参数 接收一个函数 上传数据中断时会触发
>         },
>          // 以下所有设置都和vue-quill-editor本身所对应
>         placeholder: 'Write something...',  // 可选参数 富文本框内的提示语
>         // theme: '',  // 可选参数 富文本编辑器的风格
>         // toolOptions: null,  // 可选参数  选择工具栏的需要哪些功能  默认是全部
>         // handlers: {}  // 可选参数 重定义的事件，比如link等事件
>       }
>     )
>     //  console.log(this.editorOption)
>   },
>   methods: {
>     onEditorBlur(quill) {
>       
>     },
>     onEditorFocus(quill) {
> 
>     },
>     onEditorReady(quill) {
> 
>     },
>     onEditorChange(e){
>       // console.log(e);
>     },
>     // onEditorChange({ quill, html, text }) {
>     //   console.log('editor change!', quill, html, text);
>     //   this.content = html;
>     // },
>   },
>   computed: {
> 
>   },
>   mounted() {
> 
>   },
> };
> </script>
> ```
> 
> ```css
> <style lang="scss">
>   .ql-editor {
>     height: 300px !important;
>   }
>   .quill-code {
>     border: none;
>     height: auto;
>     > code {
>       width: 100%;
>       margin: 0;
>       padding: 1rem;
>       border: 1px solid #ccc;
>       border-top: none;
>       border-radius: 0;
>       height: 10rem;
>       overflow-y: auto;
>       resize: vertical;
>     }
>   }
> </style>
> ```

Thank you very much for your help. Now I cannot achieve the effect when introducing quill-emoji, could you please help me in this area

**Comment by finebo** [comment]
你是否解决了这个问题

Have you solved the problem

**Comment by finebo** [comment]
你是否解决了这个问题

Have you solved the problem

**Comment by RexHung0302** [comment]
Do you have demo code? 

I guess you didn't installed `quill-emoji`, if you need to use `quill-emoji` you should install it.

Use `npm install quill-emoji` or `yarn add quill-emoji` and can  customize by [quill-emoji document](https://github.com/contentco/quill-emoji)

**Comment by finebo** [comment]
yes,I have the demo,if you have time,I can provide my code for you tomorrow,



---Original---

**Comment by finebo** [comment]
<template>
  <div
    <quill-editor
            class="seditor"
            v-model="contentvalue"
            ref="myQuillEditor"
            :options="editorOption"
            @blur="onEditorBlur($event)"
            @focus="onEditorFocus($event)"
            @change="onEditorChange($event)">
    </quill-editor>
    <div class="img_Loadimg" @click="openImageUpload"></div>
  </div>
</template>
<script>
import { quillEditor } from 'vue-quill-editor'
import quillEmoji from 'quill-emoji'
import * as Quill from 'quill'
import '../../assets/icons/quillemoji.css'
import '../../assets/icons/quillSnow.css'
import '../../assets/icons/quillfont.css'

var color1 = ['#000000', '#FFF', '#EEECE1', '#1F497D', '#4F81BD', '#C0504D', '#9BBB59', '#8064A2', '#4BACC6', '#F79646']
var color2 = ['#F2F2F2', '#7F7F7F', '#DDD9C3', '#C6D9F0', '#DBE5F1', '#F2DCDB', '#EBF1DD', '#E5E0EC', '#DBEEF3', '#FDEADA']
var color3 = ['#d8d8d8', '#595959', '#C4BD97', '#8DB3E2', '#B8CCE4', '#E5B9B7', '#D7E3BC', '#CCC1D9', '#B7DDE8', '#FBD5B5']
var color4 = ['#BFBFBF', '#3F3F3F', '#938953', '#548DD4', '#95B3D7', '#D99694', '#C3D69B', '#B2A2C7', '#92CDDC', '#FAC08F']
var color5 = ['#A5A5A5', '#262626', '#494429', '#17365D', '#366092', '#953734', '#76923C', '#5F497A', '#31859B', '#E36C09']
var color6 = ['#7F7F7F', '#0C0C0C', '#1D1B10', '#0F243E', '#244061', '#632423', '#4F6128', '#3F3151', '#205867', '#974806']
var color7 = ['#A10000', '#C00000', '#FFC000', '#FFFF00', '#92D050', '#00B050', '#00B0F0', '#0070C0', '#002060', '#8090AC']
var COLORS = [ ...color1, ...color2, ...color3, ...color4, ...color5, ...color6, ...color7 ]
var fonts = ['SimSun', 'SimHei', 'Microsoft-YaHei', 'KaiTi', 'FangSong', 'Arial', 'Times-New-Roman', 'sans-serif', false]
var SIZES = [false, '10px', '12px', '14px', '16px', '17px', '18px', '20px', '22px', '24px', '26px', '28px', '30px', '32px']

var Font = Quill.import('attributors/style/font')
var Size = Quill.import('attributors/style/size')
Font.whitelist = fonts // 将字体加入到白名单
Size.whitelist = SIZES // 将字体加入到白名单
Quill.register(Font, true)
Quill.register(Size, true)
Quill.register('modules/emoji-shortname', quillEmoji.ShortNameEmoji)
// 工具栏配置
console.log(quillEmoji)
const toolbarOptions = [
  ['bold'], // 加粗 斜体 下划线 删除线, 'italic', 'underline', 'strike'
  [{ header: 1 }, { header: 2 }], // 1、2 级标题
  [{ size: SIZES }], // 字体大小
  [{ color: COLORS }, { background: COLORS }], // 字体颜色、字体背景颜色
  [{ font: fonts }], // 字体种类
  [{ align: [] }], // 对齐方式
  ['link', 'image', 'video'], // 链接、图片、视频
  ['emoji'] // 小黄豆
]

export default {
  props: {
    /* 编辑器的内容 */
    content: {
      type: String
    },
    /* 图片大小 */
    maxSize: {
      type: Number,
      default: 4000 // kb
    }
  },
  components: {
    quillEditor
  },
  data () {
    return {
      contentvalue: this.content,
      quillUpdateImg: false, // 根据图片上传状态来确定是否显示loading动画，刚开始是false,不显示
      editorOption: {
        theme: 'snow', // or 'bubble'
        placeholder: '您想说点什么？',
        modules: {
          toolbar: {
            container: toolbarOptions,
            ToolbarEmoji: true,
            ShortNameEmoji: true,
            TextAreaEmoji: true,
            handlers: {
              image: function (value) {
                if (value) {
                  document.querySelector('.img_Loadimg').click()
                } else {
                  this.quill.format('image', false)
                }
              },
              emoji: function () {}
            }
          }
        }
      },
      serverUrl: '/v1/blog/imgUpload', // 这里写你要上传的图片服务器地址
      header: {
        // token: sessionStorage.token
      } // 有的图片服务器要求请求头需要有token
    }
  },
  watch: {
    content (value) {
      this.contentvalue = value
    }
  },
  methods: {
    onEditorBlur () {
      // 失去焦点事件
    },
    onEditorFocus () {
      // 获得焦点事件
    },
    onEditorChange () {
      // 内容改变事件
      this.$emit('input', this.contentvalue)
    },
    openImageUpload () {
      this.$emit('openimg')
    }
  }
}
</script>

<style>
  .seditor {
    line-height: normal !important;
    height: 500px;
  }
  .ql-snow .ql-tooltip[data-mode=link]::before {
    content: "请输入链接地址:";
  }
  .ql-snow .ql-tooltip.ql-editing a.ql-action::after {
    border-right: 0px;
    content: '保存';
    padding-right: 0px;
  }
</style>

I use vue-quill-editor, emoji is introduced, there are no errors, but the emoticon icon is not displayed, and there is no click event
![截屏2020-03-24下午4 56 34](https://user-images.githubusercontent.com/22856474/77407123-a1a8e300-6df0-11ea-995b-5a14233ee5f5.png)
![截屏2020-03-24下午4 56 25](https://user-images.githubusercontent.com/22856474/77407132-a79ec400-6df0-11ea-8c28-68208d379129.png)
我执行了npm

**Comment by RexHung0302** [comment]
有錯誤訊息嗎？

**Comment by finebo** [comment]
没有报错信息，下面的截图就是我的控制台



---Original---

**Comment by finebo** [comment]
我确信引入了emoji 模块，但是始终不能生效，我可以打印出quillemoji实例
