### ISSUE TITLE
Unknown custom element: <md-card>

### ISSUE THREAD

**Issue by wyu-prc** [surmon-china/vue-quill-editor#38]
I used the global setting. The chrome console print
Chrome console
[Vue warn]: Unknown custom element: <md-card> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

main.js
import Vue from 'vue'
import router from './router'
import VueResource from 'vue-resource'
import vuexStore from './store/store'
import VueQuillEditor from 'vue-quill-editor'
import App from './App'

Vue.use(VueQuillEditor)

new Vue({
  el: '#app',
  router: router,
  store: vuexStore,
  template: '<App/>',
  components: { App }
})

**Comment by surmon-china** [comment]
The <md-card> tag is used for example project, delete is will be work.
