### ISSUE TITLE
How vue-quill-editor combine with the syntax highlighter module of highlight.js

### ISSUE THREAD

**Issue by goforward01** [surmon-china/vue-quill-editor#39]
As the document of quill said, I add the highlight.js in my page.Well, no matter where I put the library in my html file, it always run out with the issue: **Error: Syntax module requires highlight.js. Please include the library on the page before Quill.**, I searched a lot, but with no luck. Sorry, I know here isn't the place to ask question like that, but I really couldn't figure out how to solve this. So if anyone knows solutions about that, any suggestion will be appreciated, Thx.

**Comment by goforward01** [comment]
Thanks for so rapid answer.and the html file looks like below:
`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>jzver</title>
    <link rel="stylesheet" href="dist/styles.css">
    <link href="static/monokai-sublime.min.css" rel="stylesheet">
    <script type="text/javascript" href="static/highlight.min.js"></script>
  </head>
  <body>
    <div id="root-container" style="height: 100%">
      <router-view ></router-view>
    </div>
    <script src="/dist/main.js"></script>
  </body>
</html>`
I already install the vue-quill-editor according to the readme of the project.BTW, I use the vue-quill-editor in SPA just like the demo you give:
`<template>
  
  <quill-editor v-model="content"
                ref="myQuillEditor"
                :options="editorOption"
                @blur="onEditorBlur($event)"
                @focus="onEditorFocus($event)"
                @ready="onEditorReady($event)">
  </quill-editor>

  
  <quill-editor :content="content"
                :options="editorOption"
                @change="onEditorChange($event)">
  </quill-editor>
</template>

<script>
  // You can also register quill modules in the component
  import Quill from 'quill'
  import { someModule } from '../yourModulePath/someQuillModule.js'
  Quill.register('modules/someModule', someModule)
  
  export default {
    data () {
      return {
        content: '<h2>I am Example</h2>',
        editorOption: {
          // some quill options
        }
      }
    },
    // if you need to manually control the data synchronization, parent component needs to explicitly emit an event instead of relying on implicit binding
    // 如果需要手动控制数据同步，父组件需要显式地处理changed事件
    methods: {
      onEditorBlur(editor) {
        console.log('editor blur!', editor)
      },
      onEditorFocus(editor) {
        console.log('editor focus!', editor)
      },
      onEditorReady(editor) {
        console.log('editor ready!', editor)
      },
      onEditorChange({ editor, html, text }) {
        console.log('editor change!', editor, html, text)
        this.content = html
      }
    },
    // get the current quill instace object.
    computed: {
      editor() {
        return this.$refs.myQuillEditor.quill
      }
    },
    mounted() {
      // you can use current editor object to do something(quill methods)
      console.log('this is current quill instance object', this.editor)
    }
  }
</script>`
As the document of quill, the demo to add syntax highlighter is most like: 
`
<link href="highlight.js/monokai-sublime.min.css" rel="stylesheet">


<script href="highlight.js"></script>

<script>
hljs.configure({   // optionally configure hljs
  languages: ['javascript', 'ruby', 'python']
});

var quill = new Quill('#editor', {
  modules: {
    syntax: true,              // Include syntax module
    toolbar: [['code-block']]  // Include button in toolbar
  },
  theme: 'snow'
});
</script>`
The link of doc is :https://quilljs.com/docs/modules/syntax/. So I even tried recover the syntax module in vue-quill-editor, but the issue is still. Maybe I lost something about the lifecycle of Vue, thanks very much of your time to read this.

**Comment by goforward01** [comment]
Thanks for so rapid answer. my html file looks like:
`**  <link href="static/monokai-sublime.min.css" rel="stylesheet">
    <script type="text/javascript" href="static/highlight.min.js"></script>
  **`
And I used the vue-quill-editor for my SPA pro, for now the component just like the demo you give in the main page of this pro.
I put the code above in my **head** flag or after the **body** flag, neither way work. And the link of quill about the syntax highlight is: [https://quilljs.com/docs/modules/syntax/](url).Thanks very much for your time, I'm new in Vue.js, maybe I lost something about the lifecycle of Vue component.

**Comment by surmon-china** [comment]
Is it a vue webpack project?

**Comment by surmon-china** [comment]
Try this code.
```javascript
  // in your main.js
  import 'highlight.js'
  import 'highlight.js/styles/monokai-sublime.min.css'
  import VueQuillEditor from 'vue-quill-editor'
  // ...
```

or

```vue
<template>
  <quill-editor v-model="content" :options="editorOption"></quill-editor>
</template>

<script>
  import 'highlight.js/styles/monokai-sublime.min.css'
  import 'highlight.js'
  import Quill from 'quill'
  
  export default {
    // something...
  }
</script>
```

**Comment by goforward01** [comment]
It's a vue webpack project. I gave a shot about the suggestions above, well, it still report the same error as before. I'm not sure if the order of import will be loaded in run time. I would try again and make some experiments about the load order of lib file. thanks surmon-china, could you give me some advise about these~

**Comment by surmon-china** [comment]
https://github.com/quilljs/quill/blob/develop/docs/docs/modules/syntax.md

https://github.com/quilljs/quill/blob/develop/modules/syntax.js#L68

https://github.com/quilljs/quill/blob/develop/modules/syntax.js#L41

**Comment by surmon-china** [comment]
In fact, this is because quill internal self-closure caused by the problem, the solution is as follows: `modules.syntax` from `true` to replace a `function`:

```javascript
editorOption: {
  modules: {
    syntax: {
      highlight: text => window.hljs.highlightAuto(text).value
      // or
      /*
      highlight(text) {
        const result = window.hljs.highlightAuto(text)
        return result.value
      }
      */
    }
  },
  theme: 'snow'
}
```

Other parts remain the same, highlight.js still need to be introduced before the introduction of quill.

```javascript
import hljs from 'highlight.js'
import 'highlight.js/styles/monokai-sublime.css'
```

<img width="606" alt="wx20170417-120323 2x" src="https://cloud.githubusercontent.com/assets/14019524/25078555/aa4ced3a-2366-11e7-9a8d-632a51f8269a.png">

Enjoy your work!

**Comment by goforward01** [comment]
Wow, Thanks a lot, your save me tons of time. @surmon-china

**Comment by visualjerk** [comment]
If anyone wants to use this in NUXT:

* add the CSS to your **nuxt.config.js**:

``` javascript
module.exports = {

  ...

  css: [
    'highlight.js/styles/atom-one-light.css'
  ],

  ...

}
```

* import highlight.js in your component and add it to editorOptions like so:

``` javascript
import hljs from 'highlight.js'

...

editorOption: {
  theme: 'snow',
  modules: {
    syntax: {
      highlight: text => hljs.highlightAuto(text).value
    }
  }
}
```

Thanks @surmon-china for pointing out the need for a function call!

**Comment by macnie** [comment]
> In fact, this is because quill internal self-closure caused by the problem, the solution is as follows: `modules.syntax` from `true` to replace a `function`:
> 
> ```js
> editorOption: {
>   modules: {
>     syntax: {
>       highlight: text => window.hljs.highlightAuto(text).value
>       // or
>       /*
>       highlight(text) {
>         const result = window.hljs.highlightAuto(text)
>         return result.value
>       }
>       */
>     }
>   },
>   theme: 'snow'
> }
> ```
> 
> Other parts remain the same, highlight.js still need to be introduced before the introduction of quill.
> 
> ```js
> import hljs from 'highlight.js'
> import 'highlight.js/styles/monokai-sublime.css'
> ```
> 
> <img alt="wx20170417-120323 2x" width="606" src="https://cloud.githubusercontent.com/assets/14019524/25078555/aa4ced3a-2366-11e7-9a8d-632a51f8269a.png">
> 
> Enjoy your work!

index.vue?0dbc:150 Uncaught TypeError: Cannot read property 'highlightAuto' of undefined

**Comment by gywgithub** [comment]
@macnie  add hightlight config, like this

~~~
...
<script>
import hljs from 'highlightjs'
hljs.configure({
  languages: ['javascript', 'python']
})
import 'highlightjs/styles/monokai-sublime.css'
import 'quill/dist/quill.snow.css'
import * as Quill from 'quill'
export default {
  data () {
    return {
      quill: null
    }
  },
  mounted () {
    this.quill = new Quill('#editor', {
      modules: {
        syntax: {
          highlight: text => hljs.highlightAuto(text).value
        },
        toolbar: '#toolbar-container'
      },
      placeholder: 'Compose an epic...',
      theme: 'snow'
    })
  },

...
~~~

**Comment by TengFeiHao** [comment]
In NUXT project,  highlight.js asynchronous change  'content'.    In  'onEditorChange(){}'   ,   'this.content'  repeated assignment.  So dead cycle.    The code and error are as follows：
`
[Vue warn]: You may have an infinite update loop in a component render function.

found in

---> <QuillEditor> at components/common/quillEditor.vue
       <Pages/detail/Index.vue> at pages/detail/_index.vue
         <Nuxt>
           <Layouts/default.vue> at layouts/default.vue
             <Root> commons.app.js:13282:7
    NuxtJS 7
`

`data() {
            return {
                content: ""
                editorOption: {
                    modules: {
                        toolbar: [ ... ],
                        syntax: {
                            highlight: text => hljs.highlightAuto(text).value
                        }
                    },
                    theme:'snow'
                },
            }
        },
        methods: {
            onEditorChange({quill, html, text}) {
                this.content = html;
            },
        }
    }`

**Comment by eserdinyo** [comment]
> Try this code.
> 
> ```js
>   // in your main.js
>   import 'highlight.js'
>   import 'highlight.js/styles/monokai-sublime.min.css'
>   import VueQuillEditor from 'vue-quill-editor'
>   // ...
> ```
> 
> or
> 
> ```
> <template>
>   <quill-editor v-model="content" :options="editorOption"></quill-editor>
> </template>
> 
> <script>
>   import 'highlight.js/styles/monokai-sublime.min.css'
>   import 'highlight.js'
>   import Quill from 'quill'
>   
>   export default {
>     // something...
>   }
> </script>
> ```

Hi. In the or part you are importing `quill` but you using `quill-edior` component. how this is happening? I don't understand.

**Comment by eserdinyo** [comment]
Ok. I guess i solved it finally.
I added this
`<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/highlight.min.js"></script>`
in the index.html.

And it's done.

**Comment by babaiwan** [comment]
> In fact, this is because quill internal self-closure caused by the problem, the solution is as follows: `modules.syntax` from `true` to replace a `function`:
> 
> ```js
> editorOption: {
>   modules: {
>     syntax: {
>       highlight: text => window.hljs.highlightAuto(text).value
>       // or
>       /*
>       highlight(text) {
>         const result = window.hljs.highlightAuto(text)
>         return result.value
>       }
>       */
>     }
>   },
>   theme: 'snow'
> }
> ```
> 
> Other parts remain the same, highlight.js still need to be introduced before the introduction of quill.
> 
> ```js
> import hljs from 'highlight.js'
> import 'highlight.js/styles/monokai-sublime.css'
> ```
> 
> <img alt="wx20170417-120323 2x" width="606" src="https://cloud.githubusercontent.com/assets/14019524/25078555/aa4ced3a-2366-11e7-9a8d-632a51f8269a.png">
> 
> Enjoy your work!



> In fact, this is because quill internal self-closure caused by the problem, the solution is as follows: `modules.syntax` from `true` to replace a `function`:
> 
> ```js
> editorOption: {
>   modules: {
>     syntax: {
>       highlight: text => window.hljs.highlightAuto(text).value
>       // or
>       /*
>       highlight(text) {
>         const result = window.hljs.highlightAuto(text)
>         return result.value
>       }
>       */
>     }
>   },
>   theme: 'snow'
> }
> ```
> 
> Other parts remain the same, highlight.js still need to be introduced before the introduction of quill.
> 
> ```js
> import hljs from 'highlight.js'
> import 'highlight.js/styles/monokai-sublime.css'
> ```
> 
> <img alt="wx20170417-120323 2x" width="606" src="https://cloud.githubusercontent.com/assets/14019524/25078555/aa4ced3a-2366-11e7-9a8d-632a51f8269a.png">
> 
> Enjoy your work!

i think i may have the solution
![image](https://user-images.githubusercontent.com/50008615/142396188-c048bcfa-688c-4cb4-b0cb-4f13e07230a5.png)
![image](https://user-images.githubusercontent.com/50008615/142396234-fe1e0c01-cea5-4f9c-bf4f-b02f99b70c8b.png)
what i need to do is to handle these message
