### ISSUE TITLE
使用 webpack UglifyJsPlugin 压缩时报错

### ISSUE THREAD

**Issue by ryannan** [surmon-china/vue-quill-editor#4]
error build.js from UnglifyJs
SyntaxError: Unexpected token punc  <<,>>, expected punc <<:>> [./vue-quill-editor/index.js:9,0]

**Comment by surmon-china** [comment]
插件内部是ES6语法，建议配置babel，或者用vue-cli工具来初始化webpack模板，插件本身不会再做低版本降级处理

**Comment by forzalianjunting** [comment]
我也有同样的问题，使用的vue-cli，已经配置了babel-loader，其它的构建时都没有这个问题
![image](https://cloud.githubusercontent.com/assets/15181706/21498138/e21f1480-cc64-11e6-8b9c-6cd78da474e5.png)

**Comment by surmon-china** [comment]
请升级到1.1.0版本
