### ISSUE TITLE
【BUG】cannot destroy toolbar

### ISSUE THREAD

**Issue by yss** [surmon-china/vue-quill-editor#40]
I found the toolbar has not been destoryed automaticly when i used it with vue2.

And i found the solution.

firstly, change the template to
```html
<div class="quill-editor"><div></div></div>
```

secondly, change the instance of Quill which is defined in line 67:

```
self.quill = new Quill(self.$el.childNodes[0], self.options)
```

Now this problem is solved

**Comment by surmon-china** [comment]
Thanks for your feedback, I soon solved it!

**Comment by surmon-china** [comment]
v2.1.0 fix it!
