### ISSUE TITLE
When the quill-magic-url plugin is connected, the values in the editor are not initiated correctly.

### ISSUE THREAD

**Issue by v1talii-dev** [surmon-china/vue-quill-editor#459]
I created the corresponding [task in the quill-magic-url repository](https://github.com/visualjerk/quill-magic-url/issues/60), but it looks like it's a vue-quill-editor issue.
As far as I could figure it out, this is due to the `pasteHTML()` method. When I changed the local implementation of the method in all places ([1](https://github.com/surmon-china/vue-quill-editor/blob/master/src/editor.vue#L163), [2](https://github.com/surmon-china/vue-quill-editor/blob/master/src/editor.vue#L113)) to `this.quill.root.innerHTML = newVal;` then everything worked correctly. This is a bug in the vue-quill-editor plugin?

**Comment by visualjerk** [comment]
Should be fixed with version 4.1.3 of quill-magic-url.

See: https://github.com/visualjerk/quill-magic-url/issues/60
