### ISSUE TITLE
The rich text content is passed to the backend, and how the data obtained by the frontend is displayed in the editor on the page

### ISSUE THREAD

**Issue by OranHub** [surmon-china/vue-quill-editor#463]
The rich text content is passed to the backend, and how the data obtained by the frontend is displayed in the editor on the page

<quill-editor
              ref="text"
              v-model="content"
              class="myQuillEditor"
              :options="editorOption"
            />

**Comment by OranHub** [comment]
``<quill-editor
              ref="text"
              v-model="content"
              class="myQuillEditor"
              :options="editorOption"
            />

**Comment by xiaoyanzheng** [comment]
> `<quill-editor ref="text" v-model="content" class="myQuillEditor" :options="editorOption" />`

backend response data is “<p><strong><em><s><u>123</u></s></em></strong></p>”， quill editor display “<p>123</p>”，so rich text become plain text
