### ISSUE TITLE
发现删除和回车都会触发text-change事件，唯独输入文字时不会触发，这是为啥，你们没有遇到吗？

### ISSUE THREAD

**Issue by yxhlance** [surmon-china/vue-quill-editor#476]
### Describe the bug

 quill.on('text-change', function (delta, oldDelta, source) {
        var html = _this5.$refs.QuillEditor.$refs.editor.children[0].innerHTML;
        var text = quill.getText();
        _this5.content = html;
        _this5.$emit('input', _this5.content);
        _this5.$emit('change', { html: html, text: text, quill: quill });
  });
我这是在 ready 事件触发时绑定的 text-change事件

### Reproduction

<quill-editor
        class="ql-editor editor"
        @change="onChange"
        @ready="readyChange($event)"
        style="min-height: 300px;"
        v-model="content"
        :options="editorOption"
        ref="QuillEditor"
      ></quill-editor>

readyChange (quill) {
      quill.on('text-change', (delta, oldDelta, source) => {
        let html = this.$refs.QuillEditor.$refs.editor.children[0].innerHTML
        const text = quill.getText()
        this.content = html
        this.$emit('input', this.content)
        this.$emit('change', { html, text, quill })
      })
    },
onChange(value) {

      this.quillEditorFirstOpen = false
      this.$emit("input", value.html);
      this.curLength = value.html.length
    },

### System Info

```shell
window 10 台式， 谷歌浏览器版本 102.0.5005.115
```

### Used Package Manager

npm

### Validations

- [X] Read the the documentation in detail.
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a GitHub Discussion or join our [Discord Chat Server](https://discord.surmon.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yxhlance** [comment]
已经可以了，这是缓存问题

**Comment by dongpobaicai** [comment]
不是吧，我也遇到了，分要删除，空格，换行才会触发  text-change

**Comment by lazy-tomato** [comment]
我也遇到这个问题了，暂时没找到比较好的解决方式，正常的输入内容，不会触发text-change。但是回车空格删除会触发，有具体的解决方案吗？
