### ISSUE TITLE
Is there anyway to separate components between toolbox and text editor?

### ISSUE THREAD

**Issue by vannizer** [surmon-china/vue-quill-editor#5]
Is there anyway to separate components between `toolbox` and `text editor`?

I'm trying something as following below, but it won't works

template
```
  <div ref="toolbar">
    <button class="ql-bold">Bold</button>
    <button class="ql-italic">Italic</button>
  </div>
```
script
```
editorOption: {
  modules: { toolbar: this.$refs.toolbar }
}
```

**Comment by surmon-china** [comment]
Provide more detailed code please .

**Comment by surmon-china** [comment]
As the quill toolbar does not support the dom element of the object in the form of configuration, so for the time being only in the form of custom id toolbar, follow-up I will explore a better solution.

**Comment by surmon-china** [comment]
#7

**Comment by surmon-china** [comment]
https://github.com/quilljs/quill/issues/581 #

**Comment by surmon-china** [comment]
v1.2.2 fix it.
