### ISSUE TITLE
关于设置:disabled="true"无效的bug

### ISSUE THREAD

**Issue by xiterjia** [surmon-china/vue-quill-editor#50]
开发中遇到的问题，暂无示例代码
`props` 中添加的有对 `disabled` 的传值，`watch` `disabled`的时候也对 `this.quill` 作了判断，当页面代码比较复杂的时候，创建编辑器是需要花费一些时间，有可能还未创建成功时，针对`disabled`的`watch`已经触发，就无法在默认渲染时控制编辑器是否可用。

我的想法，`emit ready`事件的时候，再重新设置一下disabled的值

> self.$emit('ready', self.quill)
> self.quill.enable(!this.disabled)
`由于设置props无用，我在@ready里可以控制编辑器的disabled ，是可以正常启作用的:) `

**Comment by surmon-china** [comment]
已采纳，待更新
