### ISSUE TITLE
在ios中无法输入

### ISSUE THREAD

**Issue by xiaomak** [surmon-china/vue-quill-editor#54]
我在ydui中使用这编辑，但是在ios不能输入，不出现光标，但是能弹出输入法，打的字无法输入到编辑器里，Android倒是正常。我用的是iphone7 IOS 10.3.2

**Comment by soapper** [comment]
同样的问题获取不到焦点

**Comment by surmon-china** [comment]
待测试

**Comment by surmon-china** [comment]
IOS 10.3.2 IP7 微信 safari chrome 实测没毛病，有焦点、会闪烁、能打字、能加粗，

要不要仔细排查下是哪的问题，输入法？

![wechatimg11](https://user-images.githubusercontent.com/14019524/27261985-c6829be4-5480-11e7-912c-c9c739fea9a3.jpeg)

**Comment by xiaomak** [comment]
官网那个是可以的，但是在项目中引用就不行了。

**Comment by surmon-china** [comment]
贴代码

**Comment by surmon-china** [comment]
测试一下 quill官网的编辑器在移动端表现如何

**Comment by xiaomak** [comment]
也是正常的，我用你这个在项目中iOS 就没有焦点，但是安卓上面是正常的

**Comment by xiaomak** [comment]
现在代码不在，我是直接参考你的写法放到项目中的

**Comment by soapper** [comment]
我已经解决了

**Comment by soapper** [comment]
查看css中user-select的值

**Comment by surmon-china** [comment]
@soapper 谢谢啊

@xiaomak 测试下

**Comment by xiaomak** [comment]
user-select用什么？

**Comment by surmon-china** [comment]
http://www.css88.com/book/css/properties/user-interface/user-select.htm 一一测试

**Comment by soapper** [comment]
是让用户能不能选择文本的值为none时候iphone无焦点

**Comment by surmon-china** [comment]
先关闭，不能用重新开

**Comment by wufeng123456** [comment]
pc也遇到获取不到焦点的问题,css使用cdn引入怎么改，被这问题弄懵了

**Comment by wufeng123456** [comment]
问题解决了 ，我遇到的问题不是  user-select属性的原因，是获取焦点的事件被vue-grid-layout拖拽事件遮挡的原因

**Comment by YuFy1314** [comment]
IOS输入之后, 那个工具栏不能fixed是为什么?  IOS软键盘弹出后fixed就失效了, 这个问题怎么解决

**Comment by CXY037** [comment]
> IOS输入之后, 那个工具栏不能fixed是为什么? IOS软键盘弹出后fixed就失效了, 这个问题怎么解决

/**
   * 处理iOS 微信客户端6.7.4 键盘收起页面未下移bug
   */
  ; (/iphone|ipod|ipad/i.test(navigator.appVersion)) && document.addEventListener('blur', (e) => {
    // 这里加了个类型判断，因为a等元素也会触发blur事件
    ['input', 'textarea'].includes(e.target.localName) && document.body.scrollIntoView(true)
  }, true)

**Comment by YuFy1314** [comment]
@CXY037 感谢回答, 之后有时间试试您的这个方法, 这个方法在您那边试过是好使的对么?

**Comment by cishengbuhuan** [comment]
请问下在iOS11下必须双击才能获取焦点，这个问题最终的解决方案是什么呢？

**Comment by liweina-fans** [comment]
> 问题解决了 ，我遇到的问题不是 user-select属性的原因，是获取焦点的事件被vue-grid-layout拖拽事件遮挡的原因

Hi，我也遇到同样问题，您是如何解决的呢

**Comment by fengqiaoyun** [comment]
> 请问下在iOS11下必须双击才能获取焦点，这个问题最终的解决方案是什么呢？

哈喽，我也遇到了，请问你是怎么解决的啊
