### ISSUE TITLE
How to enable only specified formats?

### ISSUE THREAD

**Issue by Yliaho** [surmon-china/vue-quill-editor#55]
Hey,

First of all, I'm pretty new to all of this, so excuse me if this is obvious...

How do I allow only specified formats in the Quill editor? For example binding the `quillEditor` to options data object with `formats: ['italic']` gives me warnings on console  

```
quill:toolbar ignoring attaching to disabled format bold <button type=​"button" class=​"ql-bold">​…​</button>​
```  

It does nothing beyond that.

**Comment by surmon-china** [comment]
https://quilljs.com/docs/formats/

**Comment by fish-ball** [comment]
The same problem..

**Comment by hbsoftco** [comment]
I have `nuxt-i18n` package for multilanguage in my website. I use persian (fa) language and English (en) language.

First determine your website language, then set class to p tag.
```  
  if (this.$i18n.locale === "fa")
     this.message =  `<p class="ql-align-right ql-direction-rtl"> </p>`;
   else
      this.message =  `<p> </p>`;
 ```
