### ISSUE TITLE
If i use chinese input methods, the editor will lose the focus,when the style is changed

### ISSUE THREAD

**Issue by chenyihao2621023** [surmon-china/vue-quill-editor#58]
If Using chinese  input methods,the editor will lose the focus at the second Chinese characters,when i change style(font color,font size and so on).
But English input method is ok. I want to know how to deal with the proplem,thx!

**Comment by chenyihao2621023** [comment]
已测 是搜狗输入法的问题，切换微软自带输入法没问题，但是会出现删除不掉的bug

**Comment by chenyihao2621023** [comment]
已测 是搜狗输入法的问题，换成微软自带输入法可以，但是会出现 删除不掉的bug

**Comment by xyzshen** [comment]
输入文字出现首字母。。。怎么解决呢？

**Comment by surmon-china** [comment]
@xyzshen #56
