### ISSUE TITLE
照着作者说的一步步做， 一直报错，真的烦

### ISSUE THREAD

**Issue by zgj233** [surmon-china/vue-quill-editor#59]
Property or method "EditorChange" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.
# 我只能说我是定义了EditorChange 这个方法的， 真的不知道作者的 ReadME.md 里面的示例到底是拿来干嘛的， 就是用不起，也没有任何出现这种问题的说明。
## 你文档写好点儿不行么！

**Comment by surmon-china** [comment]
请放弃使用🙂

**Comment by shaoxiong789** [comment]
我估计你@change 写成了 :change，看看我猜的对不对

**Comment by ritayzy** [comment]
> ReadME.md

@zgj233 你的 README.md 的文件名也写错了 🤐

**Comment by lihsai0** [comment]
这是开源社区，不是评价的地方。请提交非bug以外的issue

**Comment by shaoxiong789** [comment]
下次遇到这种问题，可以把代码截图，发出来
