### ISSUE TITLE
p tag auto generated

### ISSUE THREAD

**Issue by xralphack** [surmon-china/vue-quill-editor#63]
in database
```
<p></p>
<h2></h2>

```
using v-model to insert in editor, but the html will be
```
<p></p>
<p></p>
<h2></h2>
```

is anyone has this problem?

**Comment by mikunalpha** [comment]
I use below code to remove extra <p><br></p> before code-block, maybe you can modify it to solve your problem temporarily.
```
onEditorReady (editor) {
  let qlEditor = null
  for (let i = 0; i < editor.container.childNodes.length; i++) {
    if (editor.container.childNodes[i].className === 'ql-editor') {
      qlEditor = editor.container.childNodes[i]
      break
    }
  }
  if (qlEditor === null) return
  for (let i = 0; i < qlEditor.childNodes.length; i++) {
    if (qlEditor.childNodes[i].nextSibling.className !== 'ql-syntax') {
      continue
    }
    if (qlEditor.childNodes[i].innerHTML === '<br>') {
      qlEditor.removeChild(qlEditor.childNodes[i])
    }
  }
}
```

**Comment by surmon-china** [comment]
Sorry, I can't understand this problem?

**Comment by xralphack** [comment]
@surmon-china 

p tag before h tag will be auto generated

**Comment by surmon-china** [comment]
https://github.com/quilljs/quill/issues/1516

https://github.com/quilljs/quill/blob/fba09b116146f7403c9be6ccfabf3d08a83f1acb/core/quill.js#L101

**Comment by bologer** [comment]
@surmon-china you may you regex, see [this](https://github.com/quilljs/quill/issues/163#issuecomment-427551866)
