### ISSUE TITLE
Compatibility with vue-loader 13.x

### ISSUE THREAD

**Issue by Christilut** [surmon-china/vue-quill-editor#65]
I'm importing vue-quill-editor like this:
```js
import Quill from 'quill'
import quillEditor from 'vue-quill-editor'
import ImageResize from 'quill-image-resize-module'

Quill.register('modules/imageResize', ImageResize)

export default {
  components: {
    QuillEditor: quillEditor
  }
}
```

But this results in the following error when using vue-loader 13.x:
```
[Vue warn]: Failed to mount component: template or render function not defined.
```

See https://github.com/vuejs/vue-loader/releases/tag/v13.0.0 for the breaking change

Is there a correct import syntax for this? I can't figure it out

**Comment by surmon-china** [comment]
v2.2.4 fix it.
