### ISSUE TITLE
import VueQuillEditor from 'vue-quill-editor' 只写了这一句，就报错，vue-quill-editor下载过了

### ISSUE THREAD

**Issue by shuyanzi** [surmon-china/vue-quill-editor#66]
[HMR] bundle has 3 errors
client.js?d90c:161 ./~/_css-loader@0.28.4@css-loader!./~/_vue-style-loader@3.0.1@vue-style-loader!./~/_css-loader@0.28.4@css-loader?{"minimize":false,"sourceMap":false}!./~/_quill@1.3.0@quill/dist/quill.snow.css
Module build failed: Unknown word (5:1)

  3 | // load the styles
  4 | var content = require("!!../../_css-loader@0.28.4@css-loader/index.js?{\"minimize\":false,\"sourceMap\":false}!./quill.snow.css");
> 5 | if(typeof content === 'string') content = [[module.id, content, '']];
    | ^
  6 | if(content.locals) module.exports = content.locals;
  7 | // add the styles to the DOM
  8 | var update = require("!../../_vue-style-loader@3.0.1@vue-style-loader/lib/addStylesClient.js")("97936c04", content, false);

 @ ./~/_quill@1.3.0@quill/dist/quill.snow.css 4:14-199 18:2-22:4 19:20-205
 @ ./~/_babel-loader@6.4.1@babel-loader/lib!./~/_vue-loader@12.2.2@vue-loader/lib/selector.js?type=script&index=0!./~/_vue-quill-editor@2.2.4@vue-quill-editor/src/editor.vue
 @ ./~/_vue-quill-editor@2.2.4@vue-quill-editor/src/editor.vue
 @ ./~/_vue-quill-editor@2.2.4@vue-quill-editor/src/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js
./~/_css-loader@0.28.4@css-loader!./~/_vue-style-loader@3.0.1@vue-style-loader!./~/_css-loader@0.28.4@css-loader?{"minimize":false,"sourceMap":false}!./~/_quill@1.3.0@quill/dist/quill.bubble.css
Module build failed: Unknown word (5:1)

  3 | // load the styles
  4 | var content = require("!!../../_css-loader@0.28.4@css-loader/index.js?{\"minimize\":false,\"sourceMap\":false}!./quill.bubble.css");
> 5 | if(typeof content === 'string') content = [[module.id, content, '']];
    | ^
  6 | if(content.locals) module.exports = content.locals;
  7 | // add the styles to the DOM
  8 | var update = require("!../../_vue-style-loader@3.0.1@vue-style-loader/lib/addStylesClient.js")("0d055795", content, false);

 @ ./~/_quill@1.3.0@quill/dist/quill.bubble.css 4:14-201 18:2-22:4 19:20-207
 @ ./~/_babel-loader@6.4.1@babel-loader/lib!./~/_vue-loader@12.2.2@vue-loader/lib/selector.js?type=script&index=0!./~/_vue-quill-editor@2.2.4@vue-quill-editor/src/editor.vue
 @ ./~/_vue-quill-editor@2.2.4@vue-quill-editor/src/editor.vue
 @ ./~/_vue-quill-editor@2.2.4@vue-quill-editor/src/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js
./~/_css-loader@0.28.4@css-loader!./~/_vue-style-loader@3.0.1@vue-style-loader!./~/_css-loader@0.28.4@css-loader?{"minimize":false,"sourceMap":false}!./~/_quill@1.3.0@quill/dist/quill.core.css
Module build failed: Unknown word (5:1)

  3 | // load the styles
  4 | var content = require("!!../../_css-loader@0.28.4@css-loader/index.js?{\"minimize\":false,\"sourceMap\":false}!./quill.core.css");
> 5 | if(typeof content === 'string') content = [[module.id, content, '']];
    | ^
  6 | if(content.locals) module.exports = content.locals;
  7 | // add the styles to the DOM
  8 | var update = require("!../../_vue-style-loader@3.0.1@vue-style-loader/lib/addStylesClient.js")("57cbfd62", content, false);

 @ ./~/_quill@1.3.0@quill/dist/quill.core.css 4:14-199 18:2-22:4 19:20-205
 @ ./~/_babel-loader@6.4.1@babel-loader/lib!./~/_vue-loader@12.2.2@vue-loader/lib/selector.js?type=script&index=0!./~/_vue-quill-editor@2.2.4@vue-quill-editor/src/editor.vue
 @ ./~/_vue-quill-editor@2.2.4@vue-quill-editor/src/editor.vue
 @ ./~/_vue-quill-editor@2.2.4@vue-quill-editor/src/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

**Comment by surmon-china** [comment]
#10 
#8

**Comment by wdmtech** [comment]
https://github.com/webpack-contrib/css-loader/issues/295#issuecomment-265724126

Removing the style-loader and css-loader as in the above comment fixed this for me!
