### ISSUE TITLE
初始化時props帶入disabled無效

### ISSUE THREAD

**Issue by Chiyaoching** [surmon-china/vue-quill-editor#68]
看了一下source code，disabled props 只在watch時起作用，

但我一開始直接將disabled設值沒有辦法實現disabled功能

![1500864006953](https://user-images.githubusercontent.com/5266103/28506239-78369b32-705c-11e7-8c0e-c1970ed36fa3.jpg)

**Comment by surmon-china** [comment]
v2.3.0 优化了这个问题，请升级。
