### ISSUE TITLE
SSR Nuxt Example (Nuxt 1.0.0-rc3) BROWSER_BUILD now browser

### ISSUE THREAD

**Issue by silverbackdan** [surmon-china/vue-quill-editor#69]
This line here in your SSR example prevents using the plugin:
https://github.com/surmon-china/vue-quill-editor/blob/master/nuxt-ssr-example/nuxt-quill-plugin.js#L4

I believe this should now be `if (process.browser) { ...`

**Comment by silverbackdan** [comment]
See: https://github.com/nuxt/nuxt.js/releases/tag/1.0.0-rc3

**Comment by surmon-china** [comment]
@silverbackdan 
Yes, is the version of nuxt.js updated, you can submit a pr, very welcome!

**Comment by silverbackdan** [comment]
Sorry for the delay:
https://github.com/surmon-china/vue-quill-editor/pull/73
