### ISSUE TITLE
能否为Quill添加全屏支持

### ISSUE THREAD

**Issue by sunfaces** [surmon-china/vue-quill-editor#75]
在很多场景，文本编辑组件都只能放在一个特定大小的容器里，对于编辑来说，全屏体验会更好。
因此能否对Quill进行扩展，对full screen进行支持

**Comment by surmon-china** [comment]
This component is a simple and lightweight editor. It doesn't depend on any other resources except quill core and css. Quill is an open source prototypical editor which has a powerful extension API and module registration function. If you need any other attached functions, please program on your own or use other extention modules. Finally, please don't ask the questions like whether i can realize some function in the editor or why not. Thanks.
