### ISSUE TITLE
The same Quill CSS file is being added into the build 3 times

### ISSUE THREAD

**Issue by jackbarham** [surmon-china/vue-quill-editor#77]
There are 3 versions of the same Quill CSS being added to the development and production build.

In development, there are 3 `<styles>` all containing the same CSS code in the header and in production there is 3 version of the same CSS being processed.

Here is a copy of my CSS after `npm run build`: 

https://static.vibecast.com/example/app.4cd576690c08b1fe0d6bbacf8e905ec0.css - Scroll from the bottom up.

**Comment by surmon-china** [comment]
Yes, this is within the expected, any middleware plug-in, if you want to use when you need to facilitate the style of the package, so three different styles are necessary, otherwise the need for developers to manually introduce the style, but this and Not applicable to this project.

**Comment by jackbarham** [comment]
Cool. Fair enough, I've completely customised the styling so don't need to include the snow theme. I'll see if I can remove it manually.

**Comment by christophermiles** [comment]
@jackbarham Were you able to find a way around this? I don't quite understand why the same styles need to be included three times.

**Comment by jackbarham** [comment]
I didn't. Because of this, I used a different editor.
