### ISSUE TITLE
Multiple instances. Instance name as parameter. Dynamic name.

### ISSUE THREAD

**Issue by mikeevstropov** [surmon-china/vue-quill-editor#79]
Hi! How to pass instance name dynamically like:
```
<div v-quill="editorOption" instanceName="myEditor"></div>
```
Thank you!

**Comment by surmon-china** [comment]
The v2.3.2 will be support.

**Comment by surmon-china** [comment]
https://github.com/surmon-china/vue-quill-editor/blob/master/ssr.js#L6

1. binding.arg
`<div v-quill:myEditor="editorOption"></div>`

2. vnode.data.attrs.instanceName
`<div v-quill="editorOption" :instanceName="myEditorDynamicName"></div>`

3. element id
`<div v-quill="editorOption" id="myEditor"></div>`

3. default when empty (this default instance name is "quill")
`<div v-quill="editorOption"></div>`
