### ISSUE TITLE
Webpack Build CSS Error

### ISSUE THREAD

**Issue by masonfox** [surmon-china/vue-quill-editor#8]
Trying to add this to my Laravel app (using Elixir) and I get this build error whenever webpack compiles:

```
Uncaught SyntaxError: Unexpected token .(…) quill.snow.css?83dc:7
```
It looks like it may be related to [this](https://github.com/zenoamaro/react-quill/issues/7). Does anyone have a solution for this? It is breaking my build.

**Comment by vilenice** [comment]
me too

**Comment by surmon-china** [comment]
Sorry, I have not encountered such a problem;
Do not know your detailed development environment, webpack configuration is a problem? Is the webpack project configuration initialized with vue-cli? Please provide more detailed information in order to do the next error handling

**Comment by crow1796** [comment]
Me too

**Comment by surmon-china** [comment]
Try adding [style-loader](https://github.com/webpack/style-loader) and [css-loader](https://github.com/webpack/css-loader) parsers in the webpack, and most of these errors are caused by the parser.

**Comment by surmon-china** [comment]
@vilenice 
@masonfox 
@crow1796

**Comment by tannakartikey** [comment]
```
      noParse: /node_modules\/quill\/dist\/quill\.js/,
```

Change the solution from #7 to this
