### ISSUE TITLE
How import to nuxtjs ? 

### ISSUE THREAD

**Issue by andysay** [surmon-china/vue-quill-editor#80]
How import to nuxtjs ?

**Comment by surmon-china** [comment]
https://github.com/surmon-china/vue-quill-editor/tree/master/nuxt-ssr-example

**Comment by Nisthar** [comment]
@surmon-china That page is deleted

**Comment by surmon-china** [comment]
https://github.com/surmon-china/vue-quill-editor/tree/master/examples/nuxt-ssr-example

**Comment by Guanyuhao** [comment]
nuxt 如何使用自定义 toolbar: '#toolbar'
