### ISSUE TITLE
修改字体大小时，直接添加类名，而不是内联样式。

### ISSUE THREAD

**Issue by MonyY** [surmon-china/vue-quill-editor#82]
![_2017-09-04t03-05-14 875z](https://user-images.githubusercontent.com/16411107/30010322-74385aa4-9161-11e7-9140-7afe8c853519.png)
选择下拉内容后，直接会在html标签上添加对应class，应该是内联样式才合理吧。

**Comment by han6054** [comment]
为什么关闭了，我也遇到这个问题
