### ISSUE TITLE
Quill Editor doesn't fit the container.

### ISSUE THREAD

**Issue by carere** [surmon-china/vue-quill-editor#83]
Hello,

My problem is that the ql-toolbar height and the ql-container height are too big for the container of the quill-editor. I tried to modify that and i didn't succeeded... It's very frustrating that the editor cannot fit into it's container.....

Here is my component, im using muse-ui. The mu-paper element is just a wrapper (div) for my component.

```
<template>
  <div class="content-widget">
    <mu-paper class="demo-paper" :zDepth="2" >
      <quill-editor
        v-model="content" 
        :options="editorOption">
      </quill-editor>
    </mu-paper>
  </div>
</template>

<script>
export default {
  name: 'privacy-widget',
  data () {
    return {
      content: '<h2>I am Example 1</h2>',
      editorOption: {}
    }
  }
}
</script>

<style lang="scss" scoped>

.content-widget {

  .mu-paper {
    position: relative;
    width: 100%;
    height: 100%;
    opacity: 0.5;
    display: inline-block;
    text-align: center;
    font-size: 200%;
  }

  .quill-editor {
    position: absolute;
    width: 100%;
    height: 100%;
  }
}

</style>
``` 

This is 3 screenshot in order to show you the size and the placement of the toolbar and container in the quill-editor's container:

The quill-editor's container:
![quill-editor-container](https://user-images.githubusercontent.com/1385328/30038553-66020aba-91c6-11e7-88dc-defa990154c6.png)

ql-toolbar:
![ql-toolbar](https://user-images.githubusercontent.com/1385328/30038565-75eaf2ac-91c6-11e7-8584-8eb9a951bbed.png)

ql-container:
![ql-container](https://user-images.githubusercontent.com/1385328/30038570-8016ad34-91c6-11e7-94ae-86853c2084e1.png)

As you can see in bottom of the last screenshot. The ql-container height is bigger than the quill-editor's container height. Anyone got an idea ? :)

**Comment by surmon-china** [comment]
In css, height: 100% depends on the nearest position for the relative height of the parent container, you set the quill-editor to absolute, then the edit area will be positioned on the mu-paper, so you see

```
ql-container.height === mu-paper.height * 100%
```

**Comment by carere** [comment]
Hello :)

The problem is when i set the height of the ql-editor, the total height of the component is the height of the ql-editor + the height of the ql-toolbar. Instead of being only the height of the ql-editor.

Here is the problem, you can see that the delta is the same size of the ql-toolbar's height.

![screenshot from 2017-09-05 14-16-05](https://user-images.githubusercontent.com/1385328/30060788-150ecb78-9245-11e7-812a-237b73fc8def.png)

How should i use this component with css ?

**Comment by carere** [comment]
Hello there, im not using this repo anymore so i close this issue.

I found another vue plugin for quill where we can specify the css for the ql container etc.

The editor is under a div, and you can specify the id in order to modify the css :)

Anyway, thx for the answer i close this issue
