### ISSUE TITLE
前台展示，后台设置好的样式丢失！

### ISSUE THREAD

**Issue by admin00001** [surmon-china/vue-quill-editor#89]
我在后台的富文本框写的好好的，各种居中、字体颜色、背景都设置hi好了，在前台插入富文本的时候全都没有！！ 我发现这是因为后台的富文本是加class在标签上的，而不是以内联的方式去放到标签里面，所以在前台要引入这段富文本的地方，必须要在页面先引入css链接和 在 包裹这段富文本的容器加个editor的class。这不是坑人吗？有没有什么好的办法解决

**Comment by surmon-china** [comment]
本就如此。

**Comment by galan99** [comment]
同样遇到了  怎么解决这个问题

**Comment by surmon-china** [comment]
要知道 Quill 本来就是这样工作的，样式不来自内链，而来自 class。

**Comment by fastfan** [comment]
@surmon-china 用vue-nuxt 这种ssr的，我只引入它的css,而不安装vue-quill-editor，我引的cdn，它会报跨域，该怎么解决

**Comment by listar** [comment]
@surmon-china 
同问这个问题，  内容标签里面的style  编辑器渲染前会清理掉style ，导致修改后再次进去预览和原先不一致

**Comment by Y-YJ** [comment]
在前台引入css文件
`    <link href="//cdn.quilljs.com/1.3.6/quill.core.css" rel="stylesheet" />`
`<link href="//cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet" />`
`<link href="//cdn.quilljs.com/1.3.6/quill.bubble.css" rel="stylesheet" />`
然后在渲染详情的元素外面加上 class="ql-editor"
例如：
` <p class="ql-editor" v-html="info.content"></p>`

**Comment by takhello** [comment]
不应这样
