### ISSUE TITLE
Insert Audio & Video like inserting Image

### ISSUE THREAD

**Issue by chenyihao2621023** [surmon-china/vue-quill-editor#93]
I would like to know whether you are planning to add a feature that will allow users to insert a video/audio file? I like the feature that quill saves the image as code. I would be very - very glad to be able to do the save for audio & video. (I actually need audio)

**Comment by surmon-china** [comment]
This component is a simple and lightweight editor. It doesn't depend on any other resources except quill core and css. Quill is an open source prototypical editor which has a powerful extension API and module registration function. If you need any other attached functions, please program on your own or use other extention modules. Finally, please don't ask the questions like whether i can realize some function in the editor or why not. Thanks.

```javascript
// if you need register quill modules, you need to introduce and register before the vue program is instantiated
import Quill from 'quill'
import { yourQuillModule } from '../yourModulePath/yourQuillModule.js'
Quill.register('modules/yourQuillModule', yourQuillModule)
```

https://quilljs.com/docs/api/#extension
