### ISSUE TITLE
Group some icons to gain place

### ISSUE THREAD

**Issue by Petrouchka** [surmon-china/vue-quill-editor#96]
I would like to suggest some modifications to gain place in the menus. Some of the icons could be grouped :

- Code and Quote with Headers :
![capture du 2017-10-15 10-58-54](https://user-images.githubusercontent.com/3955499/31583366-9e84a3ae-b19a-11e7-9ec1-b3e68a87256f.png)

- Indentation icons with left/right/center/justify icons :
![capture du 2017-10-15 10-59-52](https://user-images.githubusercontent.com/3955499/31583368-a280403a-b19a-11e7-8ac2-2abd1d0e0f3f.png)

**Comment by surmon-china** [comment]
Yes, you can refer to the quill's development documentation module section, if there are good suggestions or changes, welcome to submit pr!

**Comment by Petrouchka** [comment]
I opened a new Issue : https://github.com/quilljs/quill/issues/1771
